Ion: ion::gfx::UniformBlock Class Reference
ion::gfx::UniformBlock Class Reference
A UniformBlock is a grouping of uniforms that can be easily shared between multiple Nodes; changing a Uniform in a UniformBlock will thus automatically change it for all Nodes that share the block.
#include "uniformblock.h"
Public Types
enum Changes { kNumChanges = kNumBaseChanges }
Changes that affect this resource.
enum BaseChanges {
kLabelChanged,
kResourceChanged,
kNumBaseChanges
}
All ResourceHolders derived from this should start their own change enums from kNumBaseChanges.
Public Member Functions
UniformBlock ()
void SetResource (size_t index, ResourceKey key, ResourceBase *resource) const
Sets the resource at the passed index and key.
ResourceBase * GetResource (size_t index, ResourceKey key) const
Returns the Resource at the given index and key, or NULL if no resource was previously set at that location.
int GetResourceCount () const
Returns the number of resources that this holder holds.
size_t GetGpuMemoryUsed () const
Returns the total amount of GPU memory used by this Holder's resource.
const std::string & GetLabel () const
Returns/sets the label of this.
void SetLabel (const std::string &label)
void AddReceiver (Notifier *receiver)
Adds a Notifier to be notified.
void RemoveReceiver (Notifier *receiver)
Removes a Notifier to be notified.
size_t GetReceiverCount () const
Returns the number of Notifiers that will be notified.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
size_t AddUniform (const Uniform &uniform)
Adds a uniform to this and returns an index that can be used to refer to the uniform.
bool ReplaceUniform (size_t index, const Uniform &uniform)
Replaces the uniform at an index with the passed value, if the index is valid.
bool RemoveUniformByName (const std::string &name)
Removes the uniform with the passed name if it exists.
void ClearUniforms ()
Clears the vector of uniforms in this.
const base::AllocVector
< Uniform > & GetUniforms () const
Gets the vector of uniforms.
template<typename T >
bool SetUniformValue (size_t index, const T &value)
Sets the value of the uniform at an index if the index is valid.
template<typename T >
bool SetUniformValueAt (size_t index, size_t array_index, const T &value)
Sets the value of the array uniform at an index if the index is valid.
size_t GetUniformIndex (const std::string &name) const
Returns the index of the uniform this with the given name, if it exists.
template<typename T >
bool SetUniformByName (const std::string &name, const T &value)
Convenience function to set the value of a uniform specified by name.
template<typename T >
bool SetUniformByNameAt (const std::string &name, size_t array_index, const T &value)
Convenience function to set the value of an element of an array uniform designated by name.
void Enable (bool enable)
Enables or disables the UniformHolder.
bool IsEnabled () const
Protected Types
typedef WeakReferentPtr< Notifier > NotifierPtr
typedef AllocVector< NotifierPtr > NotifierPtrVector
Protected Member Functions
~UniformBlock () override
The destructor is protected because all base::Referent classes must have protected or private destructors.
void OnChanged (int bit) const
Forwards OnChanged to all resources.
const NotifierPtrVector & GetReceivers () const
Returns the set of Notifiers that will be notified.
void Notify () const
Notifies all contained Notifiers by calling their OnNotify().
virtual void OnNotify (const Notifier *notifier)
Subclasses can override this to provide custom behavior on notifications.
Detailed Description
A UniformBlock is a grouping of uniforms that can be easily shared between multiple Nodes; changing a Uniform in a UniformBlock will thus automatically change it for all Nodes that share the block.
Note that adding a Uniform adds a copy of the instance; to modify a uniform value use ReplaceUniform() or SetUniformValue[At]().
Todo:
(user): Actually support the following text in Ion. In OpenGL 3.1+/ES3+, UniformBlocks also share the same storage buffer object, even across multiple shader programs; simplifying the sending of uniform values to GL for multiple programs. This can vastly increase the speed of switching large sets of uniforms at once since the cost is only the const of a single value change.
Definition at line 39 of file uniformblock.h.
Member Typedef Documentation
typedef WeakReferentPtr<Notifier> ion::base::Notifier::NotifierPtr protected inherited
Definition at line 49 of file notifier.h.
typedef AllocVector<NotifierPtr> ion::base::Notifier::NotifierPtrVector protected inherited
Definition at line 50 of file notifier.h.
Member Enumeration Documentation
enum ion::gfx::ResourceHolder::BaseChanges inherited
All ResourceHolders derived from this should start their own change enums from kNumBaseChanges.
Enumerator
kLabelChanged
kResourceChanged
kNumBaseChanges
Definition at line 56 of file resourceholder.h.
enum ion::gfx::UniformBlock::Changes
Changes that affect this resource.
Enumerator
kNumChanges
Definition at line 42 of file uniformblock.h.
Constructor & Destructor Documentation
ion::gfx::UniformBlock::UniformBlock ()
Todo:
(user): Support interface blocks and buffer-backed UniformBlocks; make UniformBlocks require a block name and possibly require a BufferObject in the constructor.
Definition at line 23 of file uniformblock.cc.
ion::gfx::UniformBlock::~UniformBlock () override protected
The destructor is protected because all base::Referent classes must have protected or private destructors.
Definition at line 25 of file uniformblock.cc.
Member Function Documentation
void ion::base::Notifier::AddReceiver (Notifier * receiver) inherited
Adds a Notifier to be notified.
Does nothing if the receiver is NULL or is already in the receiver vector.
Definition at line 25 of file notifier.cc.
size_t ion::gfx::UniformHolder::AddUniform (const Uniform & uniform) inline inherited
Adds a uniform to this and returns an index that can be used to refer to the uniform.
Note that this index is invalid if ClearUniforms() is ever used, and may refer to a different uniform if the uniform is ever replaced with ReplaceUniform(). Returns base::kInvalidIndex if an attempt is made to add an invalid uniform.
Definition at line 46 of file uniformholder.h.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::IsValid(), and ion::base::kInvalidIndex.
Referenced by ion::text::BasicBuilder::UpdateUniforms(), and ion::text::OutlineBuilder::UpdateUniforms().
void ion::gfx::UniformHolder::ClearUniforms () inline inherited
Clears the vector of uniforms in this.
Definition at line 78 of file uniformholder.h.
Referenced by ion::text::BasicBuilder::UpdateUniforms(), and ion::text::OutlineBuilder::UpdateUniforms().
void ion::gfx::UniformHolder::Enable (bool enable) inline inherited
Enables or disables the UniformHolder.
Disabled holders are skipped over during rendering; their values are not sent to OpenGL. UniformHolders are enabled by default.
Definition at line 137 of file uniformholder.h.
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
size_t ion::gfx::ResourceHolder::GetGpuMemoryUsed () const inline inherited
Returns the total amount of GPU memory used by this Holder's resource.
Definition at line 78 of file resourceholder.h.
const std::string& ion::gfx::ResourceHolder::GetLabel () const inline inherited
Returns/sets the label of this.
Definition at line 89 of file resourceholder.h.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
size_t ion::base::Notifier::GetReceiverCount () const inherited
Returns the number of Notifiers that will be notified.
Definition at line 71 of file notifier.cc.
const Notifier::NotifierPtrVector & ion::base::Notifier::GetReceivers () const protected inherited
Returns the set of Notifiers that will be notified.
Definition at line 77 of file notifier.cc.
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
ResourceBase * ion::gfx::ResourceHolder::GetResource (size_t index, ResourceKey key) const inherited
Returns the Resource at the given index and key, or NULL if no resource was previously set at that location.
Definition at line 122 of file resourceholder.cc.
int ion::gfx::ResourceHolder::GetResourceCount () const inline inherited
Returns the number of resources that this holder holds.
Note that this is not necessarily the number of indices that have non-NULL resources. This can be used as a fast trivial check to see if the holder has any resources.
Definition at line 73 of file resourceholder.h.
size_t ion::gfx::UniformHolder::GetUniformIndex (const std::string & name) const inherited
Returns the index of the uniform this with the given name, if it exists.
The Uniform must have been added with AddUniform() or ReplaceUniform(). If no uniform with the name exists in this then returns ion::base::kInvalidIndex. Note that this is a relatively slow operation and should be used sparingly.
Definition at line 30 of file uniformholder.cc.
References DCHECK, ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetIndexInRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetRegistry(), ion::gfx::ShaderInputRegistry::GetSpecs(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::IsValid(), and ion::base::kInvalidIndex.
const base::AllocVector<Uniform>& ion::gfx::UniformHolder::GetUniforms () const inline inherited
Gets the vector of uniforms.
Definition at line 81 of file uniformholder.h.
Referenced by ion::text::Builder::UpdateFontImageTextureUniform(), ion::text::BasicBuilder::UpdateUniforms(), and ion::text::OutlineBuilder::UpdateUniforms().
bool ion::gfx::UniformHolder::IsEnabled () const inline inherited
Definition at line 138 of file uniformholder.h.
void ion::base::Notifier::Notify () const protected inherited
Notifies all contained Notifiers by calling their OnNotify().
Any receivers that have been destroyed will be removed from the vector of receivers.
Definition at line 81 of file notifier.cc.
References ion::base::SharedPtr< T >::Get().
void ion::gfx::ResourceHolder::OnChanged (int bit) const inline protected inherited
Forwards OnChanged to all resources.
Definition at line 326 of file resourceholder.h.
void ion::base::Notifier::OnNotify (const Notifier * notifier) protected virtual inherited
Subclasses can override this to provide custom behavior on notifications.
Definition at line 96 of file notifier.cc.
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
void ion::base::Notifier::RemoveReceiver (Notifier * receiver) inherited
Removes a Notifier to be notified.
Does nothing if the receiver is NULL or not in the set of receivers.
Definition at line 38 of file notifier.cc.
References ion::base::Shareable::GetRefCount().
Referenced by ion::gfx::AttributeArray::~AttributeArray().
bool ion::gfx::UniformHolder::RemoveUniformByName (const std::string & name) inline inherited
Removes the uniform with the passed name if it exists.
Returns true iff the uniform existed and hence got removed. Note that this will change the indices of other uniforms within the holder.
Definition at line 69 of file uniformholder.h.
References ion::base::kInvalidIndex.
bool ion::gfx::UniformHolder::ReplaceUniform (size_t index, const Uniform & uniform) inline inherited
Replaces the uniform at an index with the passed value, if the index is valid.
Returns if the replacement is successful.
Definition at line 57 of file uniformholder.h.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::IsValid().
void ion::gfx::ResourceHolder::SetLabel (const std::string & label) inline inherited
Definition at line 90 of file resourceholder.h.
void ion::gfx::ResourceHolder::SetResource (size_t index, ResourceKey key, ResourceBase * resource) const inherited
Sets the resource at the passed index and key.
The size of the internal vector is automatically managed so that it has the smallest possible size.
Definition at line 51 of file resourceholder.cc.
References DCHECK, DCHECK_EQ, ion::gfx::ResourceBase::GetKey(), and ion::gfx::ResourceBase::OnChanged().
template<typename T > bool ion::gfx::UniformHolder::SetUniformByName (const std::string & name, const T & value) inline inherited
Convenience function to set the value of a uniform specified by name.
This returns false if there is no uniform with that name or the value type does not match.
Definition at line 113 of file uniformholder.h.
References ion::base::kInvalidIndex, and value.
template<typename T > bool ion::gfx::UniformHolder::SetUniformByNameAt (const std::string & name, size_t array_index, const T & value) inline inherited
Convenience function to set the value of an element of an array uniform designated by name.
This returns false if:
There is no uniform matching name.
Value type 'T' does not match the uniform array type.
array_index exceeds the size of the uniform array.
Definition at line 125 of file uniformholder.h.
References ion::base::kInvalidIndex.
template<typename T > bool ion::gfx::UniformHolder::SetUniformValue (size_t index, const T & value) inline inherited
Sets the value of the uniform at an index if the index is valid.
Returns true if the index is valid and the set was successful (i.e., T is a valid type for the selected uniform), and false otherwise.
Definition at line 86 of file uniformholder.h.
Referenced by ion::text::Builder::UpdateFontImageTextureUniform(), ion::text::BasicBuilder::UpdateUniforms(), and ion::text::OutlineBuilder::UpdateUniforms().
template<typename T > bool ion::gfx::UniformHolder::SetUniformValueAt (size_t index, size_t array_index, const T & value) inline inherited
Sets the value of the array uniform at an index if the index is valid.
Returns true if the index is valid and the set was successful (i.e., T is a valid type for the selected uniform), and false otherwise.
Definition at line 95 of file uniformholder.h.
The documentation for this class was generated from the following files:
gfx/uniformblock.h
gfx/uniformblock.cc