Ion: TimelineSearch Class Reference
TimelineSearch Class Reference
Search all nodes in a timeline that match a predicate.
#include "timelinesearch.h"
Classes
class const_iterator
Public Member Functions
TimelineSearch (const Timeline &timeline, TimelineNode::Type node_type)
Searches nodes by type.
TimelineSearch (const Timeline &timeline, TimelineNode::Type node_type, const std::string &node_name)
Searches nodes by type and name.
TimelineSearch (const Timeline &timeline, TimelineNode::Type node_type, uint32 begin, uint32 end)
Searches nodes by type and time range.
TimelineSearch (const Timeline &timeline, TimelineNode::Type node_type, const std::string &node_name, uint32 begin, uint32 end)
Searches nodes by type, name and time range.
TimelineSearch (const Timeline &timeline, const ion::port::ThreadId &thread_id)
Searches threads by id. Returned nodes are guaranteed to be threads.
TimelineSearch (const Timeline &timeline, const Predicate &predicate)
Searches by arbitrary predicate.
const Predicate & predicate () const
const Timeline & timeline () const
bool empty () const
const_iterator begin () const
const_iterator end () const
Detailed Description
Search all nodes in a timeline that match a predicate.
Threads are visited in arbitray order (actually the order in which their TraceRecorders were created). Nodes under a thread are visited in order of increasing begin timestamps.
Definition at line 35 of file timelinesearch.h.
Constructor & Destructor Documentation
TimelineSearch::TimelineSearch (const Timeline & timeline, TimelineNode::Type node_type) inline
Searches nodes by type.
Definition at line 103 of file timelinesearch.h.
TimelineSearch::TimelineSearch (const Timeline & timeline, TimelineNode::Type node_type, const std::string & node_name) inline
Searches nodes by type and name.
Definition at line 110 of file timelinesearch.h.
TimelineSearch::TimelineSearch (const Timeline & timeline, TimelineNode::Type node_type, uint32 begin, uint32 end)
Searches nodes by type and time range.
Only nodes that start and end in the given range are returned.
TimelineSearch::TimelineSearch (const Timeline & timeline, TimelineNode::Type node_type, const std::string & node_name, uint32 begin, uint32 end) inline
Searches nodes by type, name and time range.
Only nodes that start and end in the given range are returned.
Definition at line 127 of file timelinesearch.h.
References end().
TimelineSearch::TimelineSearch (const Timeline & timeline, const ion::port::ThreadId & thread_id)
Searches threads by id. Returned nodes are guaranteed to be threads.
TimelineSearch::TimelineSearch (const Timeline & timeline, const Predicate & predicate) inline
Searches by arbitrary predicate.
Definition at line 146 of file timelinesearch.h.
Member Function Documentation
TimelineSearch::const_iterator TimelineSearch::begin () const inline
Definition at line 150 of file timelinesearch.h.
References Timeline::begin(), and Timeline::end().
Referenced by empty().
bool TimelineSearch::empty () const inline
Definition at line 71 of file timelinesearch.h.
References begin(), and end().
TimelineSearch::const_iterator TimelineSearch::end () const inline
Definition at line 158 of file timelinesearch.h.
References Timeline::end().
Referenced by empty(), and TimelineSearch().
const Predicate& TimelineSearch::predicate () const inline
Definition at line 69 of file timelinesearch.h.
Referenced by TimelineSearch::const_iterator::operator++().
const Timeline& TimelineSearch::timeline () const inline
Definition at line 70 of file timelinesearch.h.
Referenced by TimelineSearch::const_iterator::operator++().
The documentation for this class was generated from the following file:
profile/timelinesearch.h