Ion: ion::text::Font Class Reference
ion::text::Font Class Reference abstract
Font is a base class for implementation-specific representations of fonts.
#include "font.h"
Classes
struct FontMetrics
This struct represents the cumulative metrics for the font.
struct GlyphGrid
A grid representing a rendered glyph, with each grid pixel representing pixel coverage in the range (0,1).
Public Member Functions
const std::string & GetName () const
Returns the name of the font.
size_t GetSizeInPixels () const
Returns the size of the font in pixels.
size_t GetSdfPadding () const
Returns the padding value used when generating SDF glyphs from the font.
const FontMetrics & GetFontMetrics () const
Returns the FontMetrics for the font.
const GlyphGrid & GetGlyphGrid (GlyphIndex glyph_index) const
Returns the GlyphGrid for the indexed character.
void FilterGlyphs (GlyphSet *glyph_set)
Filter zero-size glyphs from glyph_set.
virtual GlyphIndex GetDefaultGlyphForChar (CharIndex char_index) const =0
Returns the index of a glyph corresponding to the given character in the default ("unicode", in practice) charmap of the font.
void AddGlyphsForAsciiCharacterRange (ion::text::CharIndex start, ion::text::CharIndex finish, ion::text::GlyphSet *glyphs)
For each character in [start,finish] adds the default glyph from font to glyphs.
virtual const Layout BuildLayout (const std::string &text, const LayoutOptions &options) const =0
Creates a layout as specified by options for a given single- or multi- line string text.
void CacheSdfGrids (const GlyphSet &glyph_set)
Makes sure that the GlyphData for each glyph in glyph_set has an SDF grid cached inside the font.
virtual void AddFallbackFont (const FontPtr &fallback)=0
Causes this font to use the font fallback as a fallback if a requested glyph is not found.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
Protected Types
typedef base::AllocMap
< GlyphIndex, GlyphGrid > GlyphMap
Convenience typedef for the map storing GlyphGrid instances.
Protected Member Functions
Font (const std::string &name, size_t size_in_pixels, size_t sdf_padding)
The constructor is protected because this is an abstract base class.
~Font () override
The destructor is protected because all base::Referent classes must have protected or private destructors.
GlyphGrid * GetMutableGlyphGrid (GlyphIndex glyph_index) const
Non-const version of GetGlyphGrid.
GlyphGrid * GetMutableGlyphGridLocked (GlyphIndex glyph_index) const
Prelocked version of GetMutableGlyphGrid.
virtual bool LoadGlyphGrid (GlyphIndex glyph_index, GlyphGrid *glyph_grid) const
Called by GetGlyphGrid() for missing glyphs.
const GlyphGrid & AddGlyph (GlyphIndex glyph_index, const GlyphGrid &glyph) const
Adds a GlyphGrid to the GlyphMap.
void SetFontMetrics (const FontMetrics &metrics)
Sets FontMetrics. SetFontMetrics() should only ever be called once.
bool CacheSdfGrid (GlyphIndex glyph_index, const base::Array2< double > &sdf_pixels)
Replaces the grid in a glyph with an SDF grid.
Protected Attributes
const size_t size_in_pixels_
Size in pixels.
Detailed Description
Font is a base class for implementation-specific representations of fonts.
It contains font metrics, glyph metrics, and rendered glyph grids.
Definition at line 43 of file font.h.
Member Typedef Documentation
typedef base::AllocMap<GlyphIndex, GlyphGrid> ion::text::Font::GlyphMap protected
Convenience typedef for the map storing GlyphGrid instances.
Definition at line 134 of file font.h.
Constructor & Destructor Documentation
ion::text::Font::Font (const std::string & name, size_t size_in_pixels, size_t sdf_padding) protected
The constructor is protected because this is an abstract base class.
Definition at line 41 of file font.cc.
ion::text::Font::~Font () override protected
The destructor is protected because all base::Referent classes must have protected or private destructors.
Definition at line 47 of file font.cc.
Member Function Documentation
virtual void ion::text::Font::AddFallbackFont (const FontPtr & fallback) pure virtual
Causes this font to use the font fallback as a fallback if a requested glyph is not found.
This is useful in internationalization cases, as few fonts contain glyphs for enough unicode codepoints to satisfy most languages.
Implemented in ion::text::FreeTypeFont, and ion::text::CoreTextFont.
const Font::GlyphGrid & ion::text::Font::AddGlyph (GlyphIndex glyph_index, const GlyphGrid & glyph) const protected
Adds a GlyphGrid to the GlyphMap.
Definition at line 81 of file font.cc.
References ion::base::IsInvalidReference().
void ion::text::Font::AddGlyphsForAsciiCharacterRange (ion::text::CharIndex start, ion::text::CharIndex finish, ion::text::GlyphSet * glyphs)
For each character in [start,finish] adds the default glyph from font to glyphs.
Since this is not well-defined for all of Unicode, enforces that [start,finish] lies within [1,127], where the character->glyph mapping is simple enough.
Definition at line 137 of file font.cc.
References DCHECK_GE, DCHECK_LE, and GetDefaultGlyphForChar().
virtual const Layout ion::text::Font::BuildLayout (const std::string & text, const LayoutOptions & options) const pure virtual
Creates a layout as specified by options for a given single- or multi- line string text.
Implemented in ion::text::FreeTypeFont, and ion::text::CoreTextFont.
bool ion::text::Font::CacheSdfGrid (GlyphIndex glyph_index, const base::Array2< double > & sdf_pixels) protected
Replaces the grid in a glyph with an SDF grid.
This is used to cache the SDF grid, since it is relatively expensive to compute. Logs an error and returns false on error.
Definition at line 110 of file font.cc.
References ion::port::ERROR, GetMutableGlyphGrid(), ion::text::Font::GlyphGrid::is_sdf, LOG, and ion::text::Font::GlyphGrid::pixels.
Referenced by CacheSdfGrids().
void ion::text::Font::CacheSdfGrids (const GlyphSet & glyph_set)
Makes sure that the GlyphData for each glyph in glyph_set has an SDF grid cached inside the font.
This assumes that the requested glyphs are available in the font. There is no real need to call this outside of Ion's internal code.
Definition at line 95 of file font.cc.
References CacheSdfGrid(), ion::text::ComputeSdfGrid(), DCHECK, GetMutableGlyphGrid(), GetSdfPadding(), ion::text::Font::GlyphGrid::is_sdf, ion::base::IsInvalidReference(), and ion::text::Font::GlyphGrid::pixels.
void ion::text::Font::FilterGlyphs (GlyphSet * glyph_set)
Filter zero-size glyphs from glyph_set.
Definition at line 125 of file font.cc.
References GetMutableGlyphGridLocked(), and ion::text::Font::GlyphGrid::IsZeroSize().
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
virtual GlyphIndex ion::text::Font::GetDefaultGlyphForChar (CharIndex char_index) const pure virtual
Returns the index of a glyph corresponding to the given character in the default ("unicode", in practice) charmap of the font.
Note that this is an ill-defined concept, as a character may well require multiple glyphs to render, or require different glyphs in different contexts, and so on. This and AddGlyphsForAsciiCharacterRange are therefore intended as a quick and dirty way to prepopulate a font with glyps so that a static FontImage can be used, and cannot be assumed to work on non-trivial (i.e., non-latin) characters. Returns zero if no glyph available.
Implemented in ion::text::FreeTypeFont, and ion::text::CoreTextFont.
Referenced by AddGlyphsForAsciiCharacterRange().
const FontMetrics& ion::text::Font::GetFontMetrics () const inline
Returns the FontMetrics for the font.
Definition at line 87 of file font.h.
Referenced by ion::text::ComputeTextSize().
const Font::GlyphGrid & ion::text::Font::GetGlyphGrid (GlyphIndex glyph_index) const
Returns the GlyphGrid for the indexed character.
Returns an invalid reference if the index does not refer to a glyph in the font.
Definition at line 49 of file font.cc.
References GetMutableGlyphGrid().
Font::GlyphGrid * ion::text::Font::GetMutableGlyphGrid (GlyphIndex glyph_index) const protected
Non-const version of GetGlyphGrid.
Definition at line 55 of file font.cc.
References GetMutableGlyphGridLocked().
Referenced by CacheSdfGrid(), CacheSdfGrids(), and GetGlyphGrid().
Font::GlyphGrid * ion::text::Font::GetMutableGlyphGridLocked (GlyphIndex glyph_index) const protected
Prelocked version of GetMutableGlyphGrid.
Definition at line 60 of file font.cc.
References DCHECK, ion::port::Mutex::IsLocked(), and LoadGlyphGrid().
Referenced by FilterGlyphs(), and GetMutableGlyphGrid().
const std::string& ion::text::Font::GetName () const inline
Returns the name of the font.
Definition at line 75 of file font.h.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
size_t ion::text::Font::GetSdfPadding () const inline
Returns the padding value used when generating SDF glyphs from the font.
Most SDF glyphs are larger than the original glyph so that the outer edges have a nice distance fall-off. The SDF glyph grids are padded by this many pixels on all sides.
Definition at line 84 of file font.h.
Referenced by CacheSdfGrids(), ion::text::BasicBuilder::UpdateUniforms(), and ion::text::OutlineBuilder::UpdateUniforms().
size_t ion::text::Font::GetSizeInPixels () const inline
Returns the size of the font in pixels.
Definition at line 78 of file font.h.
Referenced by ion::text::ComputeTextSize().
bool ion::text::Font::LoadGlyphGrid (GlyphIndex glyph_index, GlyphGrid * glyph_grid) const protected virtual
Called by GetGlyphGrid() for missing glyphs.
Child classes that load glyphs on-demand should override this method to load the result into glyph_grid. Returns true if a glyph was loaded.
Reimplemented in ion::text::FreeTypeFont, and ion::text::CoreTextFont.
Definition at line 77 of file font.cc.
Referenced by GetMutableGlyphGridLocked().
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
void ion::text::Font::SetFontMetrics (const FontMetrics & metrics) protected
Sets FontMetrics. SetFontMetrics() should only ever be called once.
Definition at line 89 of file font.cc.
References DCHECK_EQ, and ion::text::Font::FontMetrics::line_advance_height.
Referenced by ion::text::CoreTextFont::CoreTextFont(), and ion::text::FreeTypeFont::FreeTypeFont().
Member Data Documentation
const size_t ion::text::Font::size_in_pixels_ protected
Size in pixels.
Definition at line 169 of file font.h.
The documentation for this class was generated from the following files:
text/font.h
text/font.cc