Ion: ion::base::AllocationManager Class Reference
ion::base::AllocationManager Class Reference
AllocationManager is a singleton class that is used to manage Allocators used to allocate Ion objects.
#include "allocationmanager.h"
Public Member Functions
~AllocationManager ()
Static Public Member Functions
static void SetDefaultAllocationLifetime (AllocationLifetime lifetime)
Sets/returns the AllocationLifetime that is assumed when a default new() operator is used for an Allocatable.
static AllocationLifetime GetDefaultAllocationLifetime ()
static void SetDefaultAllocatorForLifetime (AllocationLifetime lifetime, const AllocatorPtr &allocator)
Sets/returns the default Allocator to use for a specific AllocationLifetime.
static const AllocatorPtr & GetDefaultAllocatorForLifetime (AllocationLifetime lifetime)
static const AllocatorPtr & GetDefaultAllocator ()
Convenience function that returns the default allocator to use when no lifetime is specified.
static const AllocatorPtr & GetMallocAllocator ()
Returns an allocator that performs conventional allocation and deallocation with malloc() and free().
static const AllocatorPtr & GetNonNullAllocator (const AllocatorPtr &allocator)
This convenience function can be used where a non-NULL Allocator pointer is needed.
Detailed Description
AllocationManager is a singleton class that is used to manage Allocators used to allocate Ion objects.
Definition at line 29 of file allocationmanager.h.
Constructor & Destructor Documentation
ion::base::AllocationManager::~AllocationManager ()
Definition at line 58 of file allocationmanager.cc.
Member Function Documentation
static AllocationLifetime ion::base::AllocationManager::GetDefaultAllocationLifetime () inline static
Definition at line 38 of file allocationmanager.h.
static const AllocatorPtr& ion::base::AllocationManager::GetDefaultAllocator () inline static
Convenience function that returns the default allocator to use when no lifetime is specified.
It returns the default allocator for the lifetime returned by GetDefaultAllocationLifetime().
Definition at line 70 of file allocationmanager.h.
static const AllocatorPtr& ion::base::AllocationManager::GetDefaultAllocatorForLifetime (AllocationLifetime lifetime) inline static
Definition at line 62 of file allocationmanager.h.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::base::Allocator::GetAllocatorForLifetime(), and ion::base::ScopedAllocation< T >::ScopedAllocation().
static const AllocatorPtr& ion::base::AllocationManager::GetMallocAllocator () inline static
Returns an allocator that performs conventional allocation and deallocation with malloc() and free().
Definition at line 77 of file allocationmanager.h.
static const AllocatorPtr& ion::base::AllocationManager::GetNonNullAllocator (const AllocatorPtr & allocator) inline static
This convenience function can be used where a non-NULL Allocator pointer is needed.
It returns the passed-in Allocator if it is not NULL; otherwise it returns the Allocator returned by GetDefaultAllocator().
Definition at line 84 of file allocationmanager.h.
References ion::base::SharedPtr< T >::Get().
Referenced by ion::image::NinePatch::BuildImage(), ion::image::ConvertFromExternalImageData(), ion::image::ConvertImage(), ion::base::Allocatable::GetNonNullAllocator(), and ion::base::Variant< GLint, GLfloat, math::Range1f, math::Range1i, GraphicsManager::ShaderPrecision, std::vector< GLint > >::InitArray().
static void ion::base::AllocationManager::SetDefaultAllocationLifetime (AllocationLifetime lifetime) inline static
Sets/returns the AllocationLifetime that is assumed when a default new() operator is used for an Allocatable.
It is MediumTerm by default.
Definition at line 35 of file allocationmanager.h.
static void ion::base::AllocationManager::SetDefaultAllocatorForLifetime (AllocationLifetime lifetime, const AllocatorPtr & allocator) inline static
Sets/returns the default Allocator to use for a specific AllocationLifetime.
The default Allocator will be used for allocations of Allocatable objects when using the new(AllocationLifetime) operator or when Ion allocates subordinate objects, unless the Allocator for the owner object overrides its GetAllocatorForLifetime() function.
By default, the Allocator returned by GetMallocAllocator() is used for all lifetimes. Setting an Allocator to NULL restores GetMallocAllocator() as the default allocator.
Note
these functions are not thread-safe, as it does not make sense for multiple threads to change the default allocation settings. Thread-specific allocation strategies can be implemented by overriding the Allocator::GetAllocatorForLifetime() function.
Definition at line 56 of file allocationmanager.h.
References ion::base::SharedPtr< T >::Get().
The documentation for this class was generated from the following files:
base/allocationmanager.h
base/allocationmanager.cc