Ion: ion::base::CircularBuffer< T > Class Template Reference
ion::base::CircularBuffer< T > Class Template Reference
Simple circular buffer class that has fixed capacity and does not grow automatically.
#include "circularbuffer.h"
Public Member Functions
CircularBuffer (size_t capacity, const ion::base::AllocatorPtr &alloc, bool do_reserve)
Create CircularBuffer with maximum size capacity allocated from alloc.
void AddItem (const T &item)
Add an item to the buffer.
const T & GetItem (size_t i) const
Return the item at position i.
size_t GetSize () const
Get the current number of items in the buffer.
size_t GetCapacity () const
Get the total capacity of the buffer.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
Detailed Description
template<typename T>
class ion::base::CircularBuffer< T >
Simple circular buffer class that has fixed capacity and does not grow automatically.
Definition at line 30 of file circularbuffer.h.
Constructor & Destructor Documentation
template<typename T > ion::base::CircularBuffer< T >::CircularBuffer (size_t capacity, const ion::base::AllocatorPtr & alloc, bool do_reserve)
Create CircularBuffer with maximum size capacity allocated from alloc.
If do_reserve is true, the full buffer capacity is allocated at the time of instantiation.
Definition at line 86 of file circularbuffer.h.
Member Function Documentation
template<typename T> void ion::base::CircularBuffer< T >::AddItem (const T & item) inline
Add an item to the buffer.
If the buffer is at full capacity, this overwrites the oldest element in the buffer.
Definition at line 40 of file circularbuffer.h.
Referenced by ion::profile::TraceRecorder::AnnotateCurrentScopeAtTime(), ion::profile::TraceRecorder::CreateTimeStampAtTime(), ion::profile::TraceRecorder::EnterFrame(), ion::profile::TraceRecorder::EnterScopeAtTime(), ion::profile::TraceRecorder::EnterTimeRange(), ion::profile::TraceRecorder::LeaveFrame(), ion::profile::TraceRecorder::LeaveScopeAtTime(), ion::profile::TraceRecorder::LeaveTimeRange(), and ion::profile::TraceRecorder::TraceRecorder().
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
template<typename T> size_t ion::base::CircularBuffer< T >::GetCapacity () const inline
Get the total capacity of the buffer.
Definition at line 72 of file circularbuffer.h.
template<typename T> const T& ion::base::CircularBuffer< T >::GetItem (size_t i) const inline
Return the item at position i.
A position of 0 refers to the oldest item recorded in the buffer, while the position (GetSize() - 1) is the newest.
Definition at line 53 of file circularbuffer.h.
Referenced by ion::profile::TraceRecorder::AddTraceToTimelineNode(), ion::profile::TraceRecorder::DumpTrace(), and ion::profile::TraceRecorder::GetNumTraces().
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
template<typename T> size_t ion::base::CircularBuffer< T >::GetSize () const inline
Get the current number of items in the buffer.
Definition at line 69 of file circularbuffer.h.
Referenced by ion::profile::TraceRecorder::AddTraceToTimelineNode(), ion::profile::TraceRecorder::DumpTrace(), and ion::profile::TraceRecorder::GetNumTraces().
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
The documentation for this class was generated from the following file:
base/circularbuffer.h