Ion: ion::gfx::ResourceHolder Class Reference
ion::gfx::ResourceHolder Class Reference
ResourceHolder is an internal base class for objects that hold resources managed by an outside entity, such as ResourceManager, allowing the resources to be associated opaquely with an instance of the object.
#include "resourceholder.h"
Classes
class Field
A generic field that represents some state in the resource.
class FieldBase
Base class for Fields (see below).
class RangedField
A Field that has a limited valid range of values.
class VectorField
A Field that holds a vector of up to some number of values.
Public Types
enum BaseChanges {
kLabelChanged,
kResourceChanged,
kNumBaseChanges
}
All ResourceHolders derived from this should start their own change enums from kNumBaseChanges.
Public Member Functions
void SetResource (size_t index, ResourceKey key, ResourceBase *resource) const
Sets the resource at the passed index and key.
ResourceBase * GetResource (size_t index, ResourceKey key) const
Returns the Resource at the given index and key, or NULL if no resource was previously set at that location.
int GetResourceCount () const
Returns the number of resources that this holder holds.
size_t GetGpuMemoryUsed () const
Returns the total amount of GPU memory used by this Holder's resource.
const std::string & GetLabel () const
Returns/sets the label of this.
void SetLabel (const std::string &label)
void AddReceiver (Notifier *receiver)
Adds a Notifier to be notified.
void RemoveReceiver (Notifier *receiver)
Removes a Notifier to be notified.
size_t GetReceiverCount () const
Returns the number of Notifiers that will be notified.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
Protected Types
typedef WeakReferentPtr< Notifier > NotifierPtr
typedef AllocVector< NotifierPtr > NotifierPtrVector
Protected Member Functions
ResourceHolder ()
The constructor is protected because this is an abstract base class.
~ResourceHolder () override
The destructor invokes the resource callback.
void OnChanged (int bit) const
Forwards OnChanged to all resources.
const NotifierPtrVector & GetReceivers () const
Returns the set of Notifiers that will be notified.
void Notify () const
Notifies all contained Notifiers by calling their OnNotify().
virtual void OnNotify (const Notifier *notifier)
Subclasses can override this to provide custom behavior on notifications.
Friends
class FieldBase
Allow FieldBase to call AddField().
class Renderer
Allow Renderer internals to modify change bits.
Detailed Description
ResourceHolder is an internal base class for objects that hold resources managed by an outside entity, such as ResourceManager, allowing the resources to be associated opaquely with an instance of the object.
This association is done explicitly with a globally unique size_t index. Additionally, the outside entity can manage multiple resources for a single ResourceHolder by giving them ResourceKeys that are unique within a given index. Note that the internal mapping between indices and sets of resources is not sparse, so using large indices will needlessly waste memory.
For example, a BufferObject may opaquely contain a derived ResourceBase managing a VBO; when the BufferObject instance is destroyed, the VBO can be released to OpenGL at some point in the future. Similarly, if the contents of the BufferObject are modified, the BufferObject can call its ResourceBases' OnChanged() methods so that they can respond.
Definition at line 52 of file resourceholder.h.
Member Typedef Documentation
typedef WeakReferentPtr<Notifier> ion::base::Notifier::NotifierPtr protected inherited
Definition at line 49 of file notifier.h.
typedef AllocVector<NotifierPtr> ion::base::Notifier::NotifierPtrVector protected inherited
Definition at line 50 of file notifier.h.
Member Enumeration Documentation
enum ion::gfx::ResourceHolder::BaseChanges
All ResourceHolders derived from this should start their own change enums from kNumBaseChanges.
Enumerator
kLabelChanged
kResourceChanged
kNumBaseChanges
Definition at line 56 of file resourceholder.h.
Constructor & Destructor Documentation
ion::gfx::ResourceHolder::ResourceHolder () protected
The constructor is protected because this is an abstract base class.
Definition at line 25 of file resourceholder.cc.
ion::gfx::ResourceHolder::~ResourceHolder () override protected
The destructor invokes the resource callback.
It is protected because all base::Referent classes must have protected or private destructors.
Definition at line 31 of file resourceholder.cc.
Member Function Documentation
void ion::base::Notifier::AddReceiver (Notifier * receiver) inherited
Adds a Notifier to be notified.
Does nothing if the receiver is NULL or is already in the receiver vector.
Definition at line 25 of file notifier.cc.
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
size_t ion::gfx::ResourceHolder::GetGpuMemoryUsed () const inline
Returns the total amount of GPU memory used by this Holder's resource.
Definition at line 78 of file resourceholder.h.
const std::string& ion::gfx::ResourceHolder::GetLabel () const inline
Returns/sets the label of this.
Definition at line 89 of file resourceholder.h.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
size_t ion::base::Notifier::GetReceiverCount () const inherited
Returns the number of Notifiers that will be notified.
Definition at line 71 of file notifier.cc.
const Notifier::NotifierPtrVector & ion::base::Notifier::GetReceivers () const protected inherited
Returns the set of Notifiers that will be notified.
Definition at line 77 of file notifier.cc.
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
ResourceBase * ion::gfx::ResourceHolder::GetResource (size_t index, ResourceKey key) const
Returns the Resource at the given index and key, or NULL if no resource was previously set at that location.
Definition at line 122 of file resourceholder.cc.
int ion::gfx::ResourceHolder::GetResourceCount () const inline
Returns the number of resources that this holder holds.
Note that this is not necessarily the number of indices that have non-NULL resources. This can be used as a fast trivial check to see if the holder has any resources.
Definition at line 73 of file resourceholder.h.
void ion::base::Notifier::Notify () const protected inherited
Notifies all contained Notifiers by calling their OnNotify().
Any receivers that have been destroyed will be removed from the vector of receivers.
Definition at line 81 of file notifier.cc.
References ion::base::SharedPtr< T >::Get().
void ion::gfx::ResourceHolder::OnChanged (int bit) const inline protected
Forwards OnChanged to all resources.
Definition at line 326 of file resourceholder.h.
void ion::base::Notifier::OnNotify (const Notifier * notifier) protected virtual inherited
Subclasses can override this to provide custom behavior on notifications.
Definition at line 96 of file notifier.cc.
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
void ion::base::Notifier::RemoveReceiver (Notifier * receiver) inherited
Removes a Notifier to be notified.
Does nothing if the receiver is NULL or not in the set of receivers.
Definition at line 38 of file notifier.cc.
References ion::base::Shareable::GetRefCount().
Referenced by ion::gfx::AttributeArray::~AttributeArray().
void ion::gfx::ResourceHolder::SetLabel (const std::string & label) inline
Definition at line 90 of file resourceholder.h.
void ion::gfx::ResourceHolder::SetResource (size_t index, ResourceKey key, ResourceBase * resource) const
Sets the resource at the passed index and key.
The size of the internal vector is automatically managed so that it has the smallest possible size.
Definition at line 51 of file resourceholder.cc.
References DCHECK, DCHECK_EQ, ion::gfx::ResourceBase::GetKey(), and ion::gfx::ResourceBase::OnChanged().
Friends And Related Function Documentation
friend class FieldBase friend
Allow FieldBase to call AddField().
Definition at line 338 of file resourceholder.h.
friend class Renderer friend
Allow Renderer internals to modify change bits.
Definition at line 340 of file resourceholder.h.
The documentation for this class was generated from the following files:
gfx/resourceholder.h
gfx/resourceholder.cc