Ion: ion::gfx::TracingHelper Class Reference
ion::gfx::TracingHelper Class Reference
This internal class is used by the GraphicsManager to print argument values when tracing OpenGL calls.
#include "tracinghelper.h"
Public Member Functions
TracingHelper ()
The constructor sets up the data necessary to map OpenGL constant values to mnemonic names.
template<typename T >
const std::string ToString (const char *arg_type, T arg)
This templated function is used to print each OpenGL function argument in a more readable way.
template<>
ION_API const std::string ToString (const char *arg_type, const char *arg)
Specialize to add quotes around strings.
template<>
ION_API const std::string ToString (const char *arg_type, char *arg)
Specialize to add quotes around strings.
template<>
ION_API const std::string ToString (const char *arg_type, const char **arg)
Specialize to print the first string in an array of strings.
template<>
ION_API const std::string ToString (const char *arg_type, unsigned char arg)
Specialize to deal with GLboolean values.
template<>
ION_API const std::string ToString (const char *arg_type, int arg)
Specialize to deal with GLenum values.
template<>
ION_API const std::string ToString (const char *arg_type, unsigned int arg)
Specialize to deal with GLenum values.
template<>
ION_API const std::string ToString (const char *arg_type, char **arg)
Detailed Description
This internal class is used by the GraphicsManager to print argument values when tracing OpenGL calls.
Definition at line 29 of file tracinghelper.h.
Constructor & Destructor Documentation
ion::gfx::TracingHelper::TracingHelper ()
The constructor sets up the data necessary to map OpenGL constant values to mnemonic names.
Definition at line 759 of file tracinghelper.cc.
Member Function Documentation
template<typename T > const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, T arg)
This templated function is used to print each OpenGL function argument in a more readable way.
Unspecialized version.
The unspecialized version just converts the type to a string in the conventional way. There are specialized versions to handle quoting strings, replacing numbers with names, etc..
Definition at line 768 of file tracinghelper.cc.
Referenced by ToString().
template<> ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, char ** arg)
ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, const char * arg)
Specialize to add quotes around strings.
Definition at line 790 of file tracinghelper.cc.
ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, char * arg)
Specialize to add quotes around strings.
Specialize the ToString() function for types that have special processing.
Definition at line 797 of file tracinghelper.cc.
ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, const char ** arg)
Specialize to print the first string in an array of strings.
Definition at line 802 of file tracinghelper.cc.
References ToString().
ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, unsigned char arg)
Specialize to deal with GLboolean values.
Definition at line 809 of file tracinghelper.cc.
template<> ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, int arg)
Specialize to deal with GLenum values.
Definition at line 825 of file tracinghelper.cc.
References name, and ion::base::StartsWith().
ION_API const std::string ion::gfx::TracingHelper::ToString (const char * arg_type, unsigned int arg)
Specialize to deal with GLenum values.
Definition at line 875 of file tracinghelper.cc.
The documentation for this class was generated from the following files:
gfx/tracinghelper.h
gfx/tracinghelper.cc