Ion: ion::gfxutils::ResourceCallback< T > Class Template Reference
ion::gfxutils::ResourceCallback< T > Class Template Reference
Class that allows blocking until a callback is called and automagically destroys itself after both Callback() and WaitForCompletion() have executed.
#include "resourcecallback.h"
Public Types
typedef base::ReferentPtr
< ResourceCallback< T >
>::Type RefPtr
Public Member Functions
ResourceCallback (bool do_wait)
const std::vector< T > & GetData () const
Returns the data received by Callback().
void Callback (const std::vector< T > &data)
This function is compatible with ResourceManager::InfoCallback, and should be used as the callback passed to ResourceManager's Request() functions.
void WaitForCompletion (std::vector< T > *data)
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
Protected Member Functions
~ResourceCallback () override
The constructor is protected because this class is derived from Referent.
Protected Attributes
std::vector< T > data_
port::Semaphore semaphore_
RefPtr callback_holder_
RefPtr wait_holder_
Detailed Description
template<typename T>
class ion::gfxutils::ResourceCallback< T >
Class that allows blocking until a callback is called and automagically destroys itself after both Callback() and WaitForCompletion() have executed.
This is accomplished by holding two references to itself.
Definition at line 33 of file resourcecallback.h.
Member Typedef Documentation
template<typename T > typedef base::ReferentPtr<ResourceCallback<T> >::Type ion::gfxutils::ResourceCallback< T >::RefPtr
Definition at line 35 of file resourcecallback.h.
Constructor & Destructor Documentation
template<typename T > ion::gfxutils::ResourceCallback< T >::ResourceCallback (bool do_wait) inline explicit
Definition at line 36 of file resourcecallback.h.
References ion::gfxutils::ResourceCallback< T >::callback_holder_, ion::port::Semaphore::Post(), ion::base::SharedPtr< T >::Reset(), ion::gfxutils::ResourceCallback< T >::semaphore_, and ion::gfxutils::ResourceCallback< T >::wait_holder_.
template<typename T > ion::gfxutils::ResourceCallback< T >::~ResourceCallback () inline override protected
The constructor is protected because this class is derived from Referent.
Definition at line 87 of file resourcecallback.h.
References ion::gfxutils::ResourceCallback< T >::callback_holder_, DCHECK, ion::base::SharedPtr< T >::Get(), and ion::gfxutils::ResourceCallback< T >::wait_holder_.
Member Function Documentation
template<typename T > void ion::gfxutils::ResourceCallback< T >::Callback (const std::vector< T > & data) inline
This function is compatible with ResourceManager::InfoCallback, and should be used as the callback passed to ResourceManager's Request() functions.
It will be called after the request has been serviced and with the requested data.
Definition at line 50 of file resourcecallback.h.
References ion::gfxutils::ResourceCallback< T >::callback_holder_, ion::gfxutils::ResourceCallback< T >::data_, ion::port::Semaphore::Post(), and ion::gfxutils::ResourceCallback< T >::semaphore_.
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
template<typename T > const std::vector<T>& ion::gfxutils::ResourceCallback< T >::GetData () const inline
Returns the data received by Callback().
Definition at line 44 of file resourcecallback.h.
References ion::gfxutils::ResourceCallback< T >::data_.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
template<typename T > void ion::gfxutils::ResourceCallback< T >::WaitForCompletion (std::vector< T > * data) inline
Definition at line 67 of file resourcecallback.h.
References ion::gfxutils::ResourceCallback< T >::callback_holder_, ion::gfxutils::ResourceCallback< T >::data_, ion::base::SharedPtr< T >::Get(), ion::gfxutils::ResourceCallback< T >::semaphore_, ion::port::Semaphore::Wait(), and ion::gfxutils::ResourceCallback< T >::wait_holder_.
Member Data Documentation
template<typename T > RefPtr ion::gfxutils::ResourceCallback< T >::callback_holder_ protected
Definition at line 94 of file resourcecallback.h.
Referenced by ion::gfxutils::ResourceCallback< T >::Callback(), ion::gfxutils::ResourceCallback< T >::ResourceCallback(), ion::gfxutils::ResourceCallback< T >::WaitForCompletion(), and ion::gfxutils::ResourceCallback< T >::~ResourceCallback().
template<typename T > std::vector<T> ion::gfxutils::ResourceCallback< T >::data_ protected
Definition at line 92 of file resourcecallback.h.
Referenced by ion::gfxutils::ResourceCallback< T >::Callback(), ion::gfxutils::ResourceCallback< T >::GetData(), and ion::gfxutils::ResourceCallback< T >::WaitForCompletion().
template<typename T > port::Semaphore ion::gfxutils::ResourceCallback< T >::semaphore_ protected
Definition at line 93 of file resourcecallback.h.
Referenced by ion::gfxutils::ResourceCallback< T >::Callback(), ion::gfxutils::ResourceCallback< T >::ResourceCallback(), and ion::gfxutils::ResourceCallback< T >::WaitForCompletion().
template<typename T > RefPtr ion::gfxutils::ResourceCallback< T >::wait_holder_ protected
Definition at line 95 of file resourcecallback.h.
Referenced by ion::gfxutils::ResourceCallback< T >::ResourceCallback(), ion::gfxutils::ResourceCallback< T >::WaitForCompletion(), and ion::gfxutils::ResourceCallback< T >::~ResourceCallback().
The documentation for this class was generated from the following file:
gfxutils/resourcecallback.h