Ion: ion::gfxutils::FilterComposer Class Reference
ion::gfxutils::FilterComposer Class Reference
Applies a fixed transformation to the output of another composer.
#include "shadersourcecomposer.h"
Public Types
typedef std::function
< std::string(const
std::string)> StringFilter
Public Member Functions
FilterComposer (const ShaderSourceComposerPtr &base, const StringFilter &transformer)
const std::string GetSource () override
Returns the source string of a shader.
bool DependsOn (const std::string &dependency) const override
Returns whether this composer depends on the named dependency, which might be a filename or some other identifier that this recognizes.
const std::string GetDependencySource (const std::string &dependency) const override
Returns the source of the passed dependency.
bool SetDependencySource (const std::string &dependency, const std::string &source) override
Requests that the composer set the source of the dependency.
const std::string GetDependencyName (unsigned int id) const override
Returns the name of a dependency identified by the passed id.
const std::vector< std::string > GetDependencyNames () const override
Returns a vector containing all names that this composer depends on, or an empty vector if there are no dependencies.
const std::vector< std::string > GetChangedDependencies () override
Determines if any dependencies have changed (e.g., if a file has changed on disk since the last call to Get(Source|DependencySource)()) and updates them.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
Detailed Description
Applies a fixed transformation to the output of another composer.
The transformation is specified as a C++11 functor.
Definition at line 156 of file shadersourcecomposer.h.
Member Typedef Documentation
typedef std::function<std::string(const std::string)> ion::gfxutils::FilterComposer::StringFilter
Definition at line 158 of file shadersourcecomposer.h.
Constructor & Destructor Documentation
ion::gfxutils::FilterComposer::FilterComposer (const ShaderSourceComposerPtr & base, const StringFilter & transformer) inline
Definition at line 159 of file shadersourcecomposer.h.
Member Function Documentation
bool ion::gfxutils::FilterComposer::DependsOn (const std::string & dependency) const inline override virtual
Returns whether this composer depends on the named dependency, which might be a filename or some other identifier that this recognizes.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 166 of file shadersourcecomposer.h.
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
const std::vector<std::string> ion::gfxutils::FilterComposer::GetChangedDependencies () inline override virtual
Determines if any dependencies have changed (e.g., if a file has changed on disk since the last call to Get(Source|DependencySource)()) and updates them.
Returns a vector containing the names of the dependencies that have changed.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 183 of file shadersourcecomposer.h.
const std::string ion::gfxutils::FilterComposer::GetDependencyName (unsigned int id) const inline override virtual
Returns the name of a dependency identified by the passed id.
The id is an integral value used by OpenGL to identify a shader file. Returns an empty string if the id is unknown or if there are no dependencies.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 177 of file shadersourcecomposer.h.
const std::vector<std::string> ion::gfxutils::FilterComposer::GetDependencyNames () const inline override virtual
Returns a vector containing all names that this composer depends on, or an empty vector if there are no dependencies.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 180 of file shadersourcecomposer.h.
const std::string ion::gfxutils::FilterComposer::GetDependencySource (const std::string & dependency) const inline override virtual
Returns the source of the passed dependency.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 169 of file shadersourcecomposer.h.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
const std::string ion::gfxutils::FilterComposer::GetSource () inline override virtual
Returns the source string of a shader.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 163 of file shadersourcecomposer.h.
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
bool ion::gfxutils::FilterComposer::SetDependencySource (const std::string & dependency, const std::string & source) inline override virtual
Requests that the composer set the source of the dependency.
Returns whether the composer actually changes the source.
Implements ion::gfxutils::ShaderSourceComposer.
Definition at line 173 of file shadersourcecomposer.h.
The documentation for this class was generated from the following file:
gfxutils/shadersourcecomposer.h