Ion: ion::text::FontImage Class Reference
ion::text::FontImage Class Reference abstract
A FontImage contains image and texture coordinate information used to render font glyphs.
#include "fontimage.h"
Classes
struct ImageData
Data for each image in the FontImage.
Public Types
enum Type {
kStatic,
kDynamic
}
Public Member Functions
Type GetType () const
Returns the type of an instance.
const FontPtr & GetFont ()
Returns the Font passed to the constructor.
size_t GetMaxImageSize ()
Returns the maximum image size passed to the constructor.
virtual const ImageData & FindImageData (const GlyphSet &glyph_set)=0
Returns a reference to an ImageData instance that best contains the requested glyphs.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
Static Public Member Functions
static bool HasAllGlyphs (const ImageData &image_data, const GlyphSet &glyph_set)
Convenience function that returns true if an ImageData instance contains all glyphs in glyph_set.
static bool HasGlyph (const ImageData &image_data, GlyphIndex glyph_index)
Convenience function that returns true if an ImageData instance contains a glyph with the given index.
static bool GetTextureCoords (const ImageData &image_data, GlyphIndex glyph_index, math::Range2f *rectangle)
Convenience function that sets rectangle to the texture coordinate rectangle to use for the indexed glyph within an ImageData instance.
Protected Member Functions
FontImage (Type type, const FontPtr &font, size_t max_image_size)
The constructor is passed the type of derived class, the Font to use, and the maximum image size (in each dimension) for an image.
~FontImage () override
The destructor is protected because all base::Referent classes must have protected or private destructors.
Detailed Description
A FontImage contains image and texture coordinate information used to render font glyphs.
An instance may contain one or more ImageData instances, each of which stores a single texture image, a set indicating which glyphs appear in the image, and a map from glyph index to a rectangle denoting the texture coordinates for that glyph.
Each texture image is in Image::kLuminance format with power-of-2 dimensions. Each pixel is an 8-bit fixed-point version of a signed-distance field (SDF) value. Values between 0 and 126 are negative, 127 is zero, and values from 128 to 255 are positive. To recover the original signed distance, scale the resulting (-1,1) value by the Font's SDF padding amount.
FontImage is an abstract base class with derived StaticFontImage and DynamicFontImage classes.
Definition at line 63 of file fontimage.h.
Member Enumeration Documentation
enum ion::text::FontImage::Type
Enumerator
kStatic
kDynamic
Definition at line 65 of file fontimage.h.
Constructor & Destructor Documentation
ion::text::FontImage::FontImage (Type type, const FontPtr & font, size_t max_image_size) protected
The constructor is passed the type of derived class, the Font to use, and the maximum image size (in each dimension) for an image.
FontImage functions.
Derived classes treat the maximum size in different ways; see their comments for details.
Definition at line 447 of file fontimage.cc.
ion::text::FontImage::~FontImage () override protected
The destructor is protected because all base::Referent classes must have protected or private destructors.
Definition at line 450 of file fontimage.cc.
Member Function Documentation
virtual const ImageData& ion::text::FontImage::FindImageData (const GlyphSet & glyph_set) pure virtual
Returns a reference to an ImageData instance that best contains the requested glyphs.
Derived classes may return invalid references in certain cases. Note that references to ImageData instances may be invalidated by subsequent calls to FindImageData().
Implemented in ion::text::DynamicFontImage, and ion::text::StaticFontImage.
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by ion::base::DataContainer::CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
const FontPtr& ion::text::FontImage::GetFont () inline
Returns the Font passed to the constructor.
Definition at line 88 of file fontimage.h.
Referenced by ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
size_t ion::text::FontImage::GetMaxImageSize () inline
Returns the maximum image size passed to the constructor.
Definition at line 91 of file fontimage.h.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
bool ion::text::FontImage::GetTextureCoords (const ImageData & image_data, GlyphIndex glyph_index, math::Range2f * rectangle) static
Convenience function that sets rectangle to the texture coordinate rectangle to use for the indexed glyph within an ImageData instance.
Returns false if the glyph is not in the ImageData.
Definition at line 452 of file fontimage.cc.
References ion::base::IsInvalidReference(), and ion::text::FontImage::ImageData::texture_rectangle_map.
Referenced by ion::text::Builder::StoreGlyphVertices().
Type ion::text::FontImage::GetType () const inline
Returns the type of an instance.
Definition at line 85 of file fontimage.h.
static bool ion::text::FontImage::HasAllGlyphs (const ImageData & image_data, const GlyphSet & glyph_set) inline static
Convenience function that returns true if an ImageData instance contains all glyphs in glyph_set.
Definition at line 101 of file fontimage.h.
References ion::text::FontImage::ImageData::glyph_set, and ion::base::IsInvalidReference().
static bool ion::text::FontImage::HasGlyph (const ImageData & image_data, GlyphIndex glyph_index) inline static
Convenience function that returns true if an ImageData instance contains a glyph with the given index.
Definition at line 111 of file fontimage.h.
References ion::text::FontImage::ImageData::glyph_set, and ion::base::IsInvalidReference().
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
The documentation for this class was generated from the following files:
text/fontimage.h
text/fontimage.cc