Ion: ion::gfx::Uniform Class Reference
ion::gfx::Uniform Class Reference
A Uniform instance represents a uniform shader argument.
#include "uniform.h"
Public Types
typedef UniformValueType HolderType
typedef UniformType ValueType
enum Tag {
kUniform,
kAttribute
}
This is only used to determine the type of a ShaderInputRegistry::Spec since Attributes and Uniforms share the space of names.
Public Member Functions
Uniform ()
The default constructor creates an invalid Uniform instance, which should never be used as is.
~Uniform ()
void MergeValuesFrom (const Uniform &replacement)
Merges the value of this with replacement if both have the same type.
bool operator== (const Uniform &other) const
bool operator!= (const Uniform &other) const
template<>
ION_API Uniform::ValueType GetTypeByValue ()
Specialize for each supported type.
template<>
ION_API Uniform::ValueType GetTypeByValue ()
template<>
ION_API Uniform::ValueType GetTypeByValue ()
template<>
ION_API Uniform::ValueType GetTypeByValue ()
template<>
ION_API Uniform::ValueType GetTypeByValue ()
bool IsValid () const
Returns true if this is a valid instance created by a ShaderInputRegistry.
const ShaderInputRegistry & GetRegistry () const
Returns the ShaderInputRegistry the shader input is defined in.
size_t GetIndexInRegistry () const
Returns the index of the shader input within the registry.
size_t GetRegistryId () const
Returns the id of the owning registry.
size_t GetArrayIndex () const
Returns the array index of this input; by default this is 0.
ValueType GetType () const
Returns the type of the shader input.
const T & GetValue () const
If this instance contains a value of type T, this returns a const reference to it.
const T & GetValueAt (size_t i) const
If this instance contains an array of values of type T with a length smaller than the passed index, this returns a const reference to the element at i.
size_t GetCount () const
Returns the number of elements in the held type.
bool Is () const
If this instance contains a value of type T, this returns true, otherwise it returns false.
bool IsArrayOf () const
If this instance contains an array of values of type T, this returns true, otherwise it returns false.
bool SetValue (const T &value)
If this instance contains a value of type T, this changes it to the new value.
bool SetValueAt (size_t i, const T &value)
If this instance contains a array of values of type T with a length larger than i, this changes the element at i to the new value.
uint64 GetStamp () const
Returns the stamp of the input.
Static Public Member Functions
static const char * GetShaderInputTypeName ()
Returns a string containing "uniform".
static const char * GetValueTypeName (const ValueType type)
Returns a string representing a uniform type.
template<typename T >
static ValueType GetTypeByValue ()
Returns the type for a templated value type.
static Tag GetTag ()
Returns the tag for this input type.
static bool GetMerged (const Uniform &base, const Uniform &replacement, Uniform *merged)
Merges replacement and base into merged.
Protected Member Functions
void SetNewStamp ()
Assigns a new stamp to this Input.
void Init (const ShaderInputRegistry &registry, size_t registry_id, size_t index_in_registry, size_t array_index, ValueType type, const T &value)
Initializes the ShaderInput to a valid state.
void InitArray (const ShaderInputRegistry &registry, size_t registry_id, size_t index_in_registry, size_t array_index, ValueType type, const T *values, size_t count, const base::AllocatorPtr &allocator)
Initializes the ShaderInput to a valid state.
const base::AllocatorPtr & GetArrayAllocator () const
Returns the allocator used to make array allocations.
Static Protected Member Functions
static uint64 GetNewStamp ()
Returns atomically post-incremented stamp.
Detailed Description
A Uniform instance represents a uniform shader argument.
A Variant is used to store the actual type-specific value, and the interface is based on that. The Uniform class is designed to be lightweight enough that instances can be copied quickly, so they can be stored in vectors, used in stacks, and so on.
Definition at line 76 of file uniform.h.
Member Typedef Documentation
typedef UniformValueType ion::gfx::ShaderInput< UniformValueType , UniformType >::HolderType inherited
Definition at line 52 of file shaderinput.h.
typedef UniformType ion::gfx::ShaderInput< UniformValueType , UniformType >::ValueType inherited
Definition at line 53 of file shaderinput.h.
Member Enumeration Documentation
enum ion::gfx::ShaderInputBase::Tag inherited
This is only used to determine the type of a ShaderInputRegistry::Spec since Attributes and Uniforms share the space of names.
Enumerator
kUniform
kAttribute
Definition at line 35 of file shaderinput.h.
Constructor & Destructor Documentation
ion::gfx::Uniform::Uniform () inline
The default constructor creates an invalid Uniform instance, which should never be used as is.
IsValid() will return false for such an instance.
Definition at line 81 of file uniform.h.
ion::gfx::Uniform::~Uniform () inline
Definition at line 82 of file uniform.h.
Member Function Documentation
const base::AllocatorPtr& ion::gfx::ShaderInput< UniformValueType , UniformType >::GetArrayAllocator () const inline protected inherited
Returns the allocator used to make array allocations.
Definition at line 207 of file shaderinput.h.
size_t ion::gfx::ShaderInput< UniformValueType , UniformType >::GetArrayIndex () const inline inherited
Returns the array index of this input; by default this is 0.
An array index is specified in the input name with square brackets, e.g., uMyArray[2] has an index of 2.
Definition at line 76 of file shaderinput.h.
size_t ion::gfx::ShaderInput< UniformValueType , UniformType >::GetCount () const inline inherited
Returns the number of elements in the held type.
This is 0 if this holds only a scalar value.
Definition at line 99 of file shaderinput.h.
size_t ion::gfx::ShaderInput< UniformValueType , UniformType >::GetIndexInRegistry () const inline inherited
Returns the index of the shader input within the registry.
This should not be called on an invalid instance.
Definition at line 67 of file shaderinput.h.
Referenced by MergeValuesFrom(), and operator==().
bool ion::gfx::Uniform::GetMerged (const Uniform & base, const Uniform & replacement, Uniform * merged) static
Merges replacement and base into merged.
Returns true if a merge was needed, false otherwise in which case replacement completely replaces base.
Definition at line 225 of file uniform.cc.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetArrayIndex(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetCount(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetIndexInRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetType(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::IsValid(), ion::gfx::kCubeMapTextureUniform, ion::gfx::kFloatUniform, ion::gfx::kFloatVector2Uniform, ion::gfx::kFloatVector3Uniform, ion::gfx::kFloatVector4Uniform, ion::gfx::kIntUniform, ion::gfx::kIntVector2Uniform, ion::gfx::kIntVector3Uniform, ion::gfx::kIntVector4Uniform, ion::gfx::kMatrix2x2Uniform, ion::gfx::kMatrix3x3Uniform, ion::gfx::kMatrix4x4Uniform, ion::gfx::kTextureUniform, ion::gfx::kUnsignedIntUniform, ion::gfx::kUnsignedIntVector2Uniform, ion::gfx::kUnsignedIntVector3Uniform, and ion::gfx::kUnsignedIntVector4Uniform.
Referenced by MergeValuesFrom().
uint64 ion::gfx::ShaderInputBase::GetNewStamp () static protected inherited
Returns atomically post-incremented stamp.
Definition at line 24 of file shaderinput.cc.
Referenced by ion::gfx::ShaderInput< UniformValueType, UniformType >::SetNewStamp().
const ShaderInputRegistry& ion::gfx::ShaderInput< UniformValueType , UniformType >::GetRegistry () const inline inherited
Returns the ShaderInputRegistry the shader input is defined in.
This will crash if called on an invalid instance.
Definition at line 63 of file shaderinput.h.
Referenced by MergeValuesFrom(), and operator==().
size_t ion::gfx::ShaderInput< UniformValueType , UniformType >::GetRegistryId () const inline inherited
Returns the id of the owning registry.
This value will not be useful if called on an invalid instance.
Definition at line 71 of file shaderinput.h.
const char * ion::gfx::Uniform::GetShaderInputTypeName () static
Returns a string containing "uniform".
Definition at line 74 of file uniform.cc.
uint64 ion::gfx::ShaderInput< UniformValueType , UniformType >::GetStamp () const inline inherited
Returns the stamp of the input.
The stamp is a global counter which is advanced any time a ShaderInput is modified. Two Uniforms with the same stamp are guaranteed to have the same values. Two Uniforms with different stamps may or may not have the same value.
Definition at line 145 of file shaderinput.h.
static Tag ion::gfx::Uniform::GetTag () inline static
Returns the tag for this input type.
Definition at line 95 of file uniform.h.
ValueType ion::gfx::ShaderInput< UniformValueType , UniformType >::GetType () const inline inherited
Returns the type of the shader input.
This should not be called on an invalid instance.
Definition at line 80 of file shaderinput.h.
Referenced by MergeValuesFrom(), and operator==().
template<typename T > Uniform::ValueType ion::gfx::Uniform::GetTypeByValue () static
Returns the type for a templated value type.
This is instantiated for all supported types
Definition at line 101 of file uniform.cc.
References CHECK, and ion::gfx::kIntUniform.
template<> ION_API Uniform::ValueType ion::gfx::Uniform::GetTypeByValue ()
Specialize for each supported type.
Definition at line 107 of file uniform.cc.
References ion::gfx::kFloatUniform.
template<> ION_API Uniform::ValueType ion::gfx::Uniform::GetTypeByValue ()
Definition at line 110 of file uniform.cc.
References ion::gfx::kIntUniform.
template<> ION_API Uniform::ValueType ion::gfx::Uniform::GetTypeByValue ()
Definition at line 113 of file uniform.cc.
References ion::gfx::kUnsignedIntUniform.
template<> ION_API Uniform::ValueType ion::gfx::Uniform::GetTypeByValue ()
Definition at line 117 of file uniform.cc.
References ion::gfx::kCubeMapTextureUniform.
template<> ION_API Uniform::ValueType ion::gfx::Uniform::GetTypeByValue ()
Definition at line 121 of file uniform.cc.
References ion::gfx::kTextureUniform.
const T& ion::gfx::ShaderInput< UniformValueType , UniformType >::GetValue () const inline inherited
If this instance contains a value of type T, this returns a const reference to it.
Otherwise, it returns an InvalidReference. This should not be called on an invalid instance.
Definition at line 85 of file shaderinput.h.
const T& ion::gfx::ShaderInput< UniformValueType , UniformType >::GetValueAt (size_t i) const inline inherited
If this instance contains an array of values of type T with a length smaller than the passed index, this returns a const reference to the element at i.
Otherwise, it returns an InvalidReference. This should not be called on an invalid instance.
Definition at line 93 of file shaderinput.h.
const char * ion::gfx::Uniform::GetValueTypeName (const ValueType type) static
Returns a string representing a uniform type.
Definition at line 78 of file uniform.cc.
References ion::gfx::kCubeMapTextureUniform, ion::gfx::kFloatUniform, ion::gfx::kFloatVector2Uniform, ion::gfx::kFloatVector3Uniform, ion::gfx::kFloatVector4Uniform, ion::gfx::kIntUniform, ion::gfx::kIntVector2Uniform, ion::gfx::kIntVector3Uniform, ion::gfx::kIntVector4Uniform, ion::gfx::kMatrix2x2Uniform, ion::gfx::kMatrix3x3Uniform, ion::gfx::kMatrix4x4Uniform, ion::gfx::kTextureUniform, ion::gfx::kUnsignedIntUniform, ion::gfx::kUnsignedIntVector2Uniform, ion::gfx::kUnsignedIntVector3Uniform, and ion::gfx::kUnsignedIntVector4Uniform.
void ion::gfx::ShaderInput< UniformValueType , UniformType >::Init (const ShaderInputRegistry & registry, size_t registry_id, size_t index_in_registry, size_t array_index, ValueType type, const T & value) inline protected inherited
Initializes the ShaderInput to a valid state.
This is passed the ShaderInputRegistry containing the shader input definition, its index within that registry, the type, and the initial value. The value is assumed to be consistent with the registered type. This function is private because only the ShaderInputRegistry class can create valid instances, enforcing type consistency.
Definition at line 170 of file shaderinput.h.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::SetNewStamp(), and type.
void ion::gfx::ShaderInput< UniformValueType , UniformType >::InitArray (const ShaderInputRegistry & registry, size_t registry_id, size_t index_in_registry, size_t array_index, ValueType type, const T * values, size_t count, const base::AllocatorPtr & allocator) inline protected inherited
Initializes the ShaderInput to a valid state.
This is passed the ShaderInputRegistry containing the shader input definition, its index within that registry, the type, and the initial set of values (or NULL to not set values). The value is assumed to be consistent with the registered type. This function is private because only the ShaderInputRegistry class can create valid instances, enforcing type consistency.
Definition at line 189 of file shaderinput.h.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::SetNewStamp(), and type.
bool ion::gfx::ShaderInput< UniformValueType , UniformType >::Is () const inline inherited
If this instance contains a value of type T, this returns true, otherwise it returns false.
Definition at line 105 of file shaderinput.h.
bool ion::gfx::ShaderInput< UniformValueType , UniformType >::IsArrayOf () const inline inherited
If this instance contains an array of values of type T, this returns true, otherwise it returns false.
Definition at line 111 of file shaderinput.h.
bool ion::gfx::ShaderInput< UniformValueType , UniformType >::IsValid () const inline inherited
Returns true if this is a valid instance created by a ShaderInputRegistry.
If this returns false, most of the other methods should not be called.
Definition at line 59 of file shaderinput.h.
void ion::gfx::Uniform::MergeValuesFrom (const Uniform & replacement)
Merges the value of this with replacement if both have the same type.
This is useful for merging partial array uniforms. replacement will replace values in this if the array ranges overlap.
Definition at line 211 of file uniform.cc.
References ion::gfx::ShaderInput< UniformValueType, UniformType >::GetIndexInRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetIndexInRegistry(), GetMerged(), ion::gfx::ShaderInput< UniformValueType, UniformType >::GetRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetType(), and ion::gfx::ShaderInput< UniformValueType, UniformType >::GetType().
bool ion::gfx::Uniform::operator!= (const Uniform & other) const inline
Definition at line 103 of file uniform.h.
bool ion::gfx::Uniform::operator== (const Uniform & other) const
Definition at line 309 of file uniform.cc.
References CHECK_UNIFORMS_EQUAL, CHECK_VECTOR_UNIFORMS_EQUAL, ion::gfx::ShaderInput< UniformValueType, UniformType >::GetIndexInRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetIndexInRegistry(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetRegistry(), ion::gfx::ShaderInput< UniformValueType, UniformType >::GetRegistry(), ion::gfx::ShaderInput< UniformValueType, UniformType >::GetType(), ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::GetType(), ion::gfx::kCubeMapTextureUniform, ion::gfx::kFloatUniform, ion::gfx::kFloatVector2Uniform, ion::gfx::kFloatVector3Uniform, ion::gfx::kFloatVector4Uniform, ion::gfx::kIntUniform, ion::gfx::kIntVector2Uniform, ion::gfx::kIntVector3Uniform, ion::gfx::kIntVector4Uniform, ion::gfx::kMatrix2x2Uniform, ion::gfx::kMatrix3x3Uniform, ion::gfx::kMatrix4x4Uniform, ion::gfx::kTextureUniform, ion::gfx::kUnsignedIntUniform, ion::gfx::kUnsignedIntVector2Uniform, ion::gfx::kUnsignedIntVector3Uniform, and ion::gfx::kUnsignedIntVector4Uniform.
void ion::gfx::ShaderInput< UniformValueType , UniformType >::SetNewStamp () inline protected inherited
Assigns a new stamp to this Input.
Definition at line 161 of file shaderinput.h.
References ion::gfx::ShaderInputBase::GetNewStamp().
bool ion::gfx::ShaderInput< UniformValueType , UniformType >::SetValue (const T & value) inline inherited
If this instance contains a value of type T, this changes it to the new value.
Otherwise, it does nothing but return false. This should not be called on an invalid instance.
Definition at line 118 of file shaderinput.h.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::SetNewStamp().
bool ion::gfx::ShaderInput< UniformValueType , UniformType >::SetValueAt (size_t i, const T & value) inline inherited
If this instance contains a array of values of type T with a length larger than i, this changes the element at i to the new value.
Otherwise, it does nothing but return false. This should not be called on an invalid instance.
Definition at line 131 of file shaderinput.h.
References ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >::SetNewStamp().
The documentation for this class was generated from the following files:
gfx/uniform.h
gfx/uniform.cc