Ion: ion::base::DataContainer Class Reference
ion::base::DataContainer Class Reference
The DataContainer class encapsulates arbitrary user data passed to Ion.
#include "datacontainer.h"
Public Types
typedef std::function< void(void
*data_to_delete)> Deleter
Generic delete function.
Public Member Functions
bool IsWipeable () const
Returns the is_wipeable setting passed to the constructor.
template<typename T >
const T * GetData () const
Returns a const data pointer.
const void * GetData () const
Default GetData() returns a const void pointer.
template<typename T >
T * GetMutableData () const
Returns a non-const data pointer.
void WipeData ()
Informs the DataContainer that the data is no longer needed and can be deleted.
void AddReceiver (Notifier *receiver)
Adds a Notifier to be notified.
void RemoveReceiver (Notifier *receiver)
Removes a Notifier to be notified.
size_t GetReceiverCount () const
Returns the number of Notifiers that will be notified.
const AllocatorPtr & GetAllocator () const
Returns the Allocator that was used for the instance.
const AllocatorPtr & GetNonNullAllocator () const
Return our allocator, or the default allocator if the instance was declared on the stack.
const AllocatorPtr & GetAllocatorForLifetime (AllocationLifetime lifetime) const
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
void * operator new (size_t size)
The standard no-parameter new operator uses the default Allocator.
void * operator new (size_t size, AllocationLifetime lifetime)
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
void * operator new (size_t size, const AllocatorPtr &allocator)
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
void * operator new (size_t size, const AllocatorPtr &allocator, void *ptr)
Special operator new for using placement new with Allocatables.
void * operator new (size_t size, void *ptr)
The placement new operator is defined conventionally.
void operator delete (void *ptr)
Define the delete operator to use specialized functions dealing with an Allocator.
void operator delete (void *ptr, AllocationLifetime lifetime)
Windows requires these (or it issues C4291 warnings).
void operator delete (void *ptr, const AllocatorPtr &allocator)
void operator delete (void *ptr, void *ptr2)
The placement delete operator does nothing, as usual.
int GetRefCount () const
GetRefCount() is part of the interface necessary for SharedPtr.
Static Public Member Functions
template<typename T >
static void ArrayDeleter (void *data_to_delete)
Generic deleters that perform the most common deletion operations.
template<typename T >
static void PointerDeleter (void *data_to_delete)
static void AllocatorDeleter (AllocatorPtr allocator, void *data_to_delete)
A deleter for data allocated by an Allocator.
template<typename T >
static DataContainerPtr Create (T *data, const Deleter &data_deleter, bool is_wipeable, const AllocatorPtr &container_allocator)
See class comment for documentation.
template<typename T >
static DataContainerPtr CreateAndCopy (const T *data, size_t count, bool is_wipeable, const AllocatorPtr &container_and_data_allocator)
See class comment for documentation.
template<typename T >
static DataContainerPtr CreateOverAllocated (size_t count, const T *data, const AllocatorPtr &container_allocator)
See class comment for documentation.
Protected Types
typedef WeakReferentPtr< Notifier > NotifierPtr
typedef AllocVector< NotifierPtr > NotifierPtrVector
Protected Member Functions
~DataContainer () override
The destructor is protected because all base::Referent classes must have protected or private destructors.
DataContainer (const Deleter &deleter, bool is_wipeable)
The constructor is protected because all allocation of DataContainers should be through the Create() functions.
const NotifierPtrVector & GetReceivers () const
Returns the set of Notifiers that will be notified.
void Notify () const
Notifies all contained Notifiers by calling their OnNotify().
virtual void OnNotify (const Notifier *notifier)
Subclasses can override this to provide custom behavior on notifications.
Detailed Description
The DataContainer class encapsulates arbitrary user data passed to Ion.
It can only be created using one of the static Create() functions, templatized on a type T. The data in the DataContainer is created and destroyed depending on which Create() function is used. The three possibilities are:
Create(T* data, Deleter data_deleter, bool is_wipeable, const AllocatorPtr& container_allocator) The internal data pointer is set to data and the DataContainer is allocated using the passed Allocator. If data_deleter is NULL, then the caller is responsible for deleting data, and is_wipeable is ignored. If data_deleter is non-NULL, then the data will be deleted by calling data_deleter on the pointer when WipeData() is called if is_wipeable is set; otherwise data_deleter is called on the pointer only when the DataContainer is destroyed. The deleter can be any std::function that properly cleans up data; ArrayDeleter, PointerDeleter, and AllocatorDeleter static functions are provided for convenience.
CreateAndCopy(const T* data, size_t count, bool is_wipeable, const AllocatorPtr& container_and_data_allocator) The DataContainer and its internal data pointer are allocated from the passed Allocator and count elements are copied from data if data is non-NULL. The data will be deleted when WipeData() is called if is_wipeable is set; otherwise it is deleted only when the DataContainer is destroyed. The deleter function is always AllocatorDeleter (see below).
CreateOverAllocated(size_t count, T* data, const AllocatorPtr& container_allocator) Over-allocates the DataContainer by count elements of type T (i.e., this is essentially malloc(sizeof(DataContainer) + sizeof(T) * count)) and copies data into the DataContainer's data if data is non-NULL. The memory is allocated using the passed Allocator. The new data is destroyed only when the DataContainer is destroyed.
Definition at line 74 of file datacontainer.h.
Member Typedef Documentation
typedef std::function<void(void* data_to_delete)> ion::base::DataContainer::Deleter
Generic delete function.
Definition at line 77 of file datacontainer.h.
typedef WeakReferentPtr<Notifier> ion::base::Notifier::NotifierPtr protected inherited
Definition at line 49 of file notifier.h.
typedef AllocVector<NotifierPtr> ion::base::Notifier::NotifierPtrVector protected inherited
Definition at line 50 of file notifier.h.
Constructor & Destructor Documentation
ion::base::DataContainer::~DataContainer () override protected
The destructor is protected because all base::Referent classes must have protected or private destructors.
Definition at line 34 of file datacontainer.cc.
ion::base::DataContainer::DataContainer (const Deleter & deleter, bool is_wipeable) protected
The constructor is protected because all allocation of DataContainers should be through the Create() functions.
Definition at line 28 of file datacontainer.cc.
Member Function Documentation
void ion::base::Notifier::AddReceiver (Notifier * receiver) inherited
Adds a Notifier to be notified.
Does nothing if the receiver is NULL or is already in the receiver vector.
Definition at line 25 of file notifier.cc.
static void ion::base::DataContainer::AllocatorDeleter (AllocatorPtr allocator, void * data_to_delete) inline static
A deleter for data allocated by an Allocator.
The AllocatorPtr is passed by value so that a std::bind that invokes the deleter will hold a strong reference to it.
Definition at line 94 of file datacontainer.h.
References DCHECK, ion::base::Allocator::DeallocateMemory(), and ion::base::SharedPtr< T >::Get().
Referenced by CreateAndCopy().
template<typename T > static void ion::base::DataContainer::ArrayDeleter (void * data_to_delete) inline static
Generic deleters that perform the most common deletion operations.
These deleters may all be passed to Create() (see above).
Definition at line 82 of file datacontainer.h.
template<typename T > static DataContainerPtr ion::base::DataContainer::Create (T * data, const Deleter & data_deleter, bool is_wipeable, const AllocatorPtr & container_allocator) inline static
See class comment for documentation.
Definition at line 129 of file datacontainer.h.
template<typename T > static DataContainerPtr ion::base::DataContainer::CreateAndCopy (const T * data, size_t count, bool is_wipeable, const AllocatorPtr & container_and_data_allocator) inline static
See class comment for documentation.
Definition at line 142 of file datacontainer.h.
References ion::base::Allocator::AllocateMemory(), AllocatorDeleter(), ion::base::SharedPtr< T >::Get(), ion::base::Allocatable::GetAllocator(), ion::base::Allocator::GetAllocatorForLifetime(), ion::base::AllocationManager::GetDefaultAllocatorForLifetime(), kNullFunction, and ion::base::kShortTerm.
template<typename T > static DataContainerPtr ion::base::DataContainer::CreateOverAllocated (size_t count, const T * data, const AllocatorPtr & container_allocator) inline static
See class comment for documentation.
Definition at line 170 of file datacontainer.h.
References kNullFunction.
const AllocatorPtr& ion::base::Allocatable::GetAllocator () const inline inherited
Returns the Allocator that was used for the instance.
This will be NULL if the instance was declared on the stack or created with normal placement new.
Definition at line 68 of file allocatable.h.
References allocator_.
Referenced by CreateAndCopy(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), and ion::text::DynamicFontImage::FindImageDataIndex().
const AllocatorPtr& ion::base::Allocatable::GetAllocatorForLifetime (AllocationLifetime lifetime) const inline inherited
Convenience function that returns the Allocator to use to allocate an object with a specific lifetime.
Definition at line 78 of file allocatable.h.
References ion::base::Allocator::GetAllocatorForLifetime().
Referenced by ion::text::BasicBuilder::BuildVertexData(), ion::text::OutlineBuilder::BuildVertexData(), ion::gfxutils::ShaderManager::CreateShaderProgram(), ion::text::DynamicFontImage::FindContainingImageDataIndex(), ion::text::DynamicFontImage::FindImageDataIndex(), ion::gfx::Renderer::Renderer(), and ion::gfx::UpdateStateTable().
template<typename T > const T* ion::base::DataContainer::GetData () const inline
Returns a const data pointer.
Definition at line 104 of file datacontainer.h.
const void* ion::base::DataContainer::GetData () const inline
Default GetData() returns a const void pointer.
Definition at line 109 of file datacontainer.h.
template<typename T > T* ion::base::DataContainer::GetMutableData () const inline
Returns a non-const data pointer.
Definition at line 115 of file datacontainer.h.
References ion::port::ERROR, and LOG.
const AllocatorPtr& ion::base::Allocatable::GetNonNullAllocator () const inline inherited
Return our allocator, or the default allocator if the instance was declared on the stack.
Definition at line 72 of file allocatable.h.
References allocator_, and ion::base::AllocationManager::GetNonNullAllocator().
size_t ion::base::Notifier::GetReceiverCount () const inherited
Returns the number of Notifiers that will be notified.
Definition at line 71 of file notifier.cc.
const Notifier::NotifierPtrVector & ion::base::Notifier::GetReceivers () const protected inherited
Returns the set of Notifiers that will be notified.
Definition at line 77 of file notifier.cc.
int ion::base::Shareable::GetRefCount () const inline inherited
GetRefCount() is part of the interface necessary for SharedPtr.
Definition at line 34 of file shareable.h.
Referenced by ion::base::Notifier::RemoveReceiver().
bool ion::base::DataContainer::IsWipeable () const inline
Returns the is_wipeable setting passed to the constructor.
Definition at line 100 of file datacontainer.h.
void ion::base::Notifier::Notify () const protected inherited
Notifies all contained Notifiers by calling their OnNotify().
Any receivers that have been destroyed will be removed from the vector of receivers.
Definition at line 81 of file notifier.cc.
References ion::base::SharedPtr< T >::Get().
void ion::base::Notifier::OnNotify (const Notifier * notifier) protected virtual inherited
Subclasses can override this to provide custom behavior on notifications.
Definition at line 96 of file notifier.cc.
void ion::base::Allocatable::operator delete (void * ptr) inline inherited
Define the delete operator to use specialized functions dealing with an Allocator.
Definition at line 109 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, AllocationLifetime lifetime) inline inherited
Windows requires these (or it issues C4291 warnings).
Definition at line 112 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, const AllocatorPtr & allocator) inline inherited
Definition at line 113 of file allocatable.h.
void ion::base::Allocatable::operator delete (void * ptr, void * ptr2) inline inherited
The placement delete operator does nothing, as usual.
Definition at line 118 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size) inline inherited
The standard no-parameter new operator uses the default Allocator.
Definition at line 84 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, AllocationLifetime lifetime) inline inherited
This overloaded version of the new operator uses the AllocationManager's default Allocator for the specified lifetime.
Definition at line 88 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator) inline inherited
This overloaded version of the new operator takes the Allocator to use directly as a parameter.
If the Allocator pointer is NULL, this uses the default Allocator.
Definition at line 95 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, const AllocatorPtr & allocator, void * ptr) inline inherited
Special operator new for using placement new with Allocatables.
Definition at line 100 of file allocatable.h.
void* ion::base::Allocatable::operator new (size_t size, void * ptr) inline inherited
The placement new operator is defined conventionally.
Definition at line 105 of file allocatable.h.
template<typename T > static void ion::base::DataContainer::PointerDeleter (void * data_to_delete) inline static
Definition at line 87 of file datacontainer.h.
void ion::base::Notifier::RemoveReceiver (Notifier * receiver) inherited
Removes a Notifier to be notified.
Does nothing if the receiver is NULL or not in the set of receivers.
Definition at line 38 of file notifier.cc.
References ion::base::Shareable::GetRefCount().
Referenced by ion::gfx::AttributeArray::~AttributeArray().
void ion::base::DataContainer::WipeData ()
Informs the DataContainer that the data is no longer needed and can be deleted.
It does this only if is_wipeable=true was passed to the constructor and there is a non-NULL deleter; otherwise, it has no effect.
Definition at line 39 of file datacontainer.cc.
The documentation for this class was generated from the following files:
base/datacontainer.h
base/datacontainer.cc