Ion: ion::base::DateTime::Range Class Reference
ion::base::DateTime::Range Class Reference
A class to contain a beginning and ending DateTime.
#include "datetime.h"
Public Member Functions
Range ()
Range (const Range &rhs)
~Range ()
const DateTime & begin () const
const DateTime & end () const
void SetBegin (const DateTime &begin)
void SetEnd (const DateTime &end)
void SetInterpolation (const Range &begin, const Range &end, float t)
Static Public Member Functions
static Range Interpolate (const Range &begin, const Range &end, float t)
Detailed Description
A class to contain a beginning and ending DateTime.
Definition at line 63 of file datetime.h.
Constructor & Destructor Documentation
ion::base::DateTime::Range::Range () inline
Definition at line 65 of file datetime.h.
ion::base::DateTime::Range::Range (const Range & rhs) inline
Definition at line 69 of file datetime.h.
References begin(), and end().
ion::base::DateTime::Range::~Range () inline
Definition at line 73 of file datetime.h.
Member Function Documentation
const DateTime& ion::base::DateTime::Range::begin () const inline
Definition at line 75 of file datetime.h.
Referenced by Range(), SetBegin(), and SetInterpolation().
const DateTime& ion::base::DateTime::Range::end () const inline
Definition at line 76 of file datetime.h.
Referenced by Range(), SetEnd(), and SetInterpolation().
static Range ion::base::DateTime::Range::Interpolate (const Range & begin, const Range & end, float t) inline static
Definition at line 88 of file datetime.h.
References SetInterpolation().
void ion::base::DateTime::Range::SetBegin (const DateTime & begin) inline
Definition at line 78 of file datetime.h.
References begin().
void ion::base::DateTime::Range::SetEnd (const DateTime & end) inline
Definition at line 79 of file datetime.h.
References end().
void ion::base::DateTime::Range::SetInterpolation (const Range & begin, const Range & end, float t) inline
Definition at line 81 of file datetime.h.
References begin(), end(), and ion::base::DateTime::Interpolate().
Referenced by Interpolate().
The documentation for this class was generated from the following file:
base/datetime.h