Ion: ion::base::Setting< T > Class Template Reference
ion::base::Setting< T > Class Template Reference
Forward references.
#include "setting.h"
Public Types
typedef std::function< void(SettingBase
*setting)> Listener
A function that is called when the value changes.
Public Member Functions
Setting (const std::string &name, const T &value, const std::string &doc_string)
Creates a new setting with the passed name, initial value, and documentation string.
Setting (const SettingGroup *group, const std::string &name, const T &value, const std::string &doc_string)
Same as above, but places the setting in the passed group.
Setting (const std::string &name, const T &value)
Convenience constructor that does not require a documentation string.
Setting (const SettingGroup *group, const std::string &name, const T &value)
Same as above, but places the setting in the passed group.
~Setting () override
const std::string ToString () const override
Returns a string version of this setting.
bool FromString (const std::string &str) override
Parses the passed string to set the value of this and returns whether the parsing was successful.
T * GetMutableValue ()
Direct value mutators.
const T & GetValue () const
void SetValue (const T &value)
operator T () const
void operator= (const T &value)
bool operator== (const T &value) const
Equality testers.
const std::string & GetName () const
Returns the name associated with this.
const std::string & GetDocString () const
Returns the documentation string associated with this.
void SetTypeDescriptor (const std::string &desc)
Sets/returns a string containing information about the Setting's type.
const std::string & GetTypeDescriptor () const
void RegisterListener (const std::string &key, const Listener &listener)
Adds a function that will be called when this setting's value changes.
void EnableListener (const std::string &key, bool enable)
Enables or disables the listener identified by key, if one exists.
void UnregisterListener (const std::string &key)
Removes the listener identified by key, if one exists.
void NotifyListeners ()
Notify listeners that this setting has changed.
Friends
bool operator== (const T &value, const Setting< T > &setting)
Detailed Description
template<typename T>
class ion::base::Setting< T >
Forward references.
A Setting holds a value of type T, and supports listeners that are notified when the setting's value changes.
The only restrictions on T are that it must have a default constructor and support the insertion and extraction operators (<< and >>). POD types, strings, and most STL containers are supported through Ion's StringToValue and ValueToString serialization routines.
Every setting creates an entry in the global SettingManager, from which they can be retrieved and modified. This is particularly useful for editing them at runtime, for example through a configuration file, scripting interface, or remote tweak interface. A setting might, for example, control what rendering algorithm to use based on the local CPU or GPU speed, or selectively enable or disable certain features for testing or localization.
Definition at line 138 of file setting.h.
Member Typedef Documentation
typedef std::function<void(SettingBase* setting)> ion::base::SettingBase::Listener inherited
A function that is called when the value changes.
Definition at line 46 of file setting.h.
Constructor & Destructor Documentation
template<typename T> ion::base::Setting< T >::Setting (const std::string & name, const T & value, const std::string & doc_string) inline
Creates a new setting with the passed name, initial value, and documentation string.
Definition at line 159 of file setting.h.
template<typename T> ion::base::Setting< T >::Setting (const SettingGroup * group, const std::string & name, const T & value, const std::string & doc_string) inline
Same as above, but places the setting in the passed group.
Definition at line 166 of file setting.h.
template<typename T> ion::base::Setting< T >::Setting (const std::string & name, const T & value) inline
Convenience constructor that does not require a documentation string.
Definition at line 174 of file setting.h.
template<typename T> ion::base::Setting< T >::Setting (const SettingGroup * group, const std::string & name, const T & value) inline
Same as above, but places the setting in the passed group.
Definition at line 180 of file setting.h.
template<typename T> ion::base::Setting< T >::~Setting () inline override
Definition at line 186 of file setting.h.
Member Function Documentation
void ion::base::SettingBase::EnableListener (const std::string & key, bool enable) inherited
Enables or disables the listener identified by key, if one exists.
Definition at line 40 of file setting.cc.
template<typename T> bool ion::base::Setting< T >::FromString (const std::string & str) inline override virtual
Parses the passed string to set the value of this and returns whether the parsing was successful.
If the parsing does not succeed then nothing should change in this.
Implements ion::base::SettingBase.
Definition at line 190 of file setting.h.
Referenced by ion::base::EnvironmentSetting< T >::EnvironmentSetting().
const std::string& ion::base::SettingBase::GetDocString () const inline inherited
Returns the documentation string associated with this.
Definition at line 59 of file setting.h.
template<typename T> T* ion::base::Setting< T >::GetMutableValue () inline
Direct value mutators.
Definition at line 201 of file setting.h.
const std::string& ion::base::SettingBase::GetName () const inline inherited
Returns the name associated with this.
Definition at line 56 of file setting.h.
const std::string& ion::base::SettingBase::GetTypeDescriptor () const inline inherited
Definition at line 66 of file setting.h.
template<typename T> const T& ion::base::Setting< T >::GetValue () const inline
Definition at line 202 of file setting.h.
void ion::base::SettingBase::NotifyListeners () inherited
Notify listeners that this setting has changed.
Definition at line 50 of file setting.cc.
Referenced by ion::base::Setting< bool >::operator=(), ion::base::Setting< std::atomic< T > >::operator=(), ion::base::Setting< bool >::SetValue(), and ion::base::Setting< std::atomic< T > >::SetValue().
template<typename T> ion::base::Setting< T >::operator T () const inline
Definition at line 207 of file setting.h.
template<typename T> void ion::base::Setting< T >::operator= (const T & value) inline
Definition at line 208 of file setting.h.
template<typename T> bool ion::base::Setting< T >::operator== (const T & value) const inline
Equality testers.
Definition at line 214 of file setting.h.
Referenced by ion::base::EnvironmentSetting< T >::operator==().
void ion::base::SettingBase::RegisterListener (const std::string & key, const Listener & listener) inherited
Adds a function that will be called when this setting's value changes.
The function is identified by the passed key. The same key must be used to remove the listener.
Definition at line 35 of file setting.cc.
void ion::base::SettingBase::SetTypeDescriptor (const std::string & desc) inline inherited
Sets/returns a string containing information about the Setting's type.
This string can be used, for example, in an interactive program to present a specialized interface for displaying or modifying the settings. See the remote::SettingHandler documentation for examples.
Definition at line 65 of file setting.h.
Referenced by ion::base::SetTypeDescriptorForType().
template<typename T> void ion::base::Setting< T >::SetValue (const T & value) inline
Definition at line 203 of file setting.h.
Referenced by ion::base::Setting< bool >::FromString(), and ion::base::Setting< std::atomic< T > >::FromString().
template<typename T> const std::string ion::base::Setting< T >::ToString () const inline override virtual
Returns a string version of this setting.
The same string may be passed to FromString to reconstruct an identical setting.
Implements ion::base::SettingBase.
Definition at line 188 of file setting.h.
void ion::base::SettingBase::UnregisterListener (const std::string & key) inherited
Removes the listener identified by key, if one exists.
Definition at line 46 of file setting.cc.
Friends And Related Function Documentation
template<typename T> bool operator== (const T & value, const Setting< T > & setting) friend
Definition at line 215 of file setting.h.
The documentation for this class was generated from the following file:
base/setting.h