var hierarchy =
[
    [ "ion::analytics::Benchmark::AccumulatedVariable", "struction_1_1analytics_1_1_benchmark_1_1_accumulated_variable.html", null ],
    [ "ion::base::Allocatable", "classion_1_1base_1_1_allocatable.html", [
      [ "ion::base::Array2< double >", "classion_1_1base_1_1_array2.html", null ],
      [ "ion::base::CircularBuffer< uint32 >", "classion_1_1base_1_1_circular_buffer.html", null ],
      [ "ion::base::Array2< T >", "classion_1_1base_1_1_array2.html", null ],
      [ "ion::base::CircularBuffer< T >", "classion_1_1base_1_1_circular_buffer.html", null ],
      [ "ion::base::FunctionCallBase", "classion_1_1base_1_1_function_call_base.html", [
        [ "ion::base::FunctionCall< ReturnType(Types...)>", "classion_1_1base_1_1_function_call_3_01_return_type_07_types_8_8_8_08_4.html", null ]
      ] ],
      [ "ion::base::MemoryZipStream", "classion_1_1base_1_1_memory_zip_stream.html", null ],
      [ "ion::base::Referent", "classion_1_1base_1_1_referent.html", [
        [ "ion::base::CallList", "classion_1_1base_1_1_call_list.html", null ],
        [ "ion::base::WeakReferent", "classion_1_1base_1_1_weak_referent.html", [
          [ "ion::base::Notifier", "classion_1_1base_1_1_notifier.html", [
            [ "ion::base::DataContainer", "classion_1_1base_1_1_data_container.html", [
              [ "ion::base::VectorDataContainer< T >", "classion_1_1base_1_1_vector_data_container.html", null ]
            ] ],
            [ "ion::gfx::Image", "classion_1_1gfx_1_1_image.html", null ],
            [ "ion::gfx::ResourceHolder", "classion_1_1gfx_1_1_resource_holder.html", [
              [ "ion::gfx::AttributeArray", "classion_1_1gfx_1_1_attribute_array.html", null ],
              [ "ion::gfx::BufferObject", "classion_1_1gfx_1_1_buffer_object.html", [
                [ "ion::gfx::IndexBuffer", "classion_1_1gfx_1_1_index_buffer.html", null ]
              ] ],
              [ "ion::gfx::FramebufferObject", "classion_1_1gfx_1_1_framebuffer_object.html", null ],
              [ "ion::gfx::Sampler", "classion_1_1gfx_1_1_sampler.html", null ],
              [ "ion::gfx::ShaderBase", "classion_1_1gfx_1_1_shader_base.html", [
                [ "ion::gfx::Shader", "classion_1_1gfx_1_1_shader.html", null ],
                [ "ion::gfx::ShaderProgram", "classion_1_1gfx_1_1_shader_program.html", null ]
              ] ],
              [ "ion::gfx::ShaderInputRegistry", "classion_1_1gfx_1_1_shader_input_registry.html", null ],
              [ "ion::gfx::TextureBase", "classion_1_1gfx_1_1_texture_base.html", [
                [ "ion::gfx::CubeMapTexture", "classion_1_1gfx_1_1_cube_map_texture.html", null ],
                [ "ion::gfx::Texture", "classion_1_1gfx_1_1_texture.html", null ]
              ] ],
              [ "ion::gfx::UniformBlock", "classion_1_1gfx_1_1_uniform_block.html", null ]
            ] ]
          ] ]
        ] ],
        [ "ion::gfx::GraphicsManager", "classion_1_1gfx_1_1_graphics_manager.html", null ],
        [ "ion::gfx::Node", "classion_1_1gfx_1_1_node.html", null ],
        [ "ion::gfx::Renderer", "classion_1_1gfx_1_1_renderer.html", null ],
        [ "ion::gfx::Shape", "classion_1_1gfx_1_1_shape.html", null ],
        [ "ion::gfx::StateTable", "classion_1_1gfx_1_1_state_table.html", null ],
        [ "ion::gfxutils::Frame", "classion_1_1gfxutils_1_1_frame.html", null ],
        [ "ion::gfxutils::ResourceCallback< T >", "classion_1_1gfxutils_1_1_resource_callback.html", null ],
        [ "ion::gfxutils::ShaderManager", "classion_1_1gfxutils_1_1_shader_manager.html", null ],
        [ "ion::gfxutils::ShaderSourceComposer", "classion_1_1gfxutils_1_1_shader_source_composer.html", [
          [ "ion::gfxutils::FilterComposer", "classion_1_1gfxutils_1_1_filter_composer.html", null ],
          [ "ion::gfxutils::IncludeComposer", "classion_1_1gfxutils_1_1_include_composer.html", [
            [ "ion::gfxutils::ZipAssetComposer", "classion_1_1gfxutils_1_1_zip_asset_composer.html", null ]
          ] ],
          [ "ion::gfxutils::StringComposer", "classion_1_1gfxutils_1_1_string_composer.html", null ]
        ] ],
        [ "ion::image::NinePatch", "classion_1_1image_1_1_nine_patch.html", null ],
        [ "ion::remote::HttpServer::RequestHandler", "classion_1_1remote_1_1_http_server_1_1_request_handler.html", [
          [ "ion::remote::CallTraceHandler", "classion_1_1remote_1_1_call_trace_handler.html", null ],
          [ "ion::remote::NodeGraphHandler", "classion_1_1remote_1_1_node_graph_handler.html", null ],
          [ "ion::remote::ResourceHandler", "struction_1_1remote_1_1_resource_handler.html", null ],
          [ "ion::remote::SettingHandler", "classion_1_1remote_1_1_setting_handler.html", null ],
          [ "ion::remote::ShaderHandler", "classion_1_1remote_1_1_shader_handler.html", null ],
          [ "ion::remote::TracingHandler", "classion_1_1remote_1_1_tracing_handler.html", null ]
        ] ],
        [ "ion::remote::HttpServer::Websocket", "classion_1_1remote_1_1_http_server_1_1_websocket.html", null ],
        [ "ion::text::Builder", "classion_1_1text_1_1_builder.html", [
          [ "ion::text::BasicBuilder", "classion_1_1text_1_1_basic_builder.html", null ],
          [ "ion::text::OutlineBuilder", "classion_1_1text_1_1_outline_builder.html", null ]
        ] ],
        [ "ion::text::Font", "classion_1_1text_1_1_font.html", [
          [ "ion::text::CoreTextFont", "classion_1_1text_1_1_core_text_font.html", null ],
          [ "ion::text::FreeTypeFont", "classion_1_1text_1_1_free_type_font.html", null ]
        ] ],
        [ "ion::text::FontImage", "classion_1_1text_1_1_font_image.html", [
          [ "ion::text::DynamicFontImage", "classion_1_1text_1_1_dynamic_font_image.html", null ],
          [ "ion::text::StaticFontImage", "classion_1_1text_1_1_static_font_image.html", null ]
        ] ],
        [ "ion::text::FontManager", "classion_1_1text_1_1_font_manager.html", null ]
      ] ],
      [ "ion::base::WorkerPool", "classion_1_1base_1_1_worker_pool.html", null ],
      [ "ion::gfx::ResourceManager", "classion_1_1gfx_1_1_resource_manager.html", null ],
      [ "ion::gfx::TextureManager", "classion_1_1gfx_1_1_texture_manager.html", null ],
      [ "ion::profile::CallTraceManager", "classion_1_1profile_1_1_call_trace_manager.html", null ],
      [ "ion::profile::TraceRecorder", "classion_1_1profile_1_1_trace_recorder.html", null ]
    ] ],
    [ "ion::base::AllocationManager", "classion_1_1base_1_1_allocation_manager.html", null ],
    [ "std::allocator< T >", null, [
      [ "ion::base::StlAllocator< T >", "classion_1_1base_1_1_stl_allocator.html", [
        [ "ion::base::StlInlinedAllocator< T, N >", "classion_1_1base_1_1_stl_inlined_allocator.html", null ]
      ] ]
    ] ],
    [ "ion::math::Angle< T >", "classion_1_1math_1_1_angle.html", null ],
    [ "ion::base::Variant< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40 >::ArrayAccessor", "struction_1_1base_1_1_variant_1_1_array_accessor.html", null ],
    [ "ion::gfx::FramebufferObject::Attachment", "classion_1_1gfx_1_1_framebuffer_object_1_1_attachment.html", null ],
    [ "ion::gfx::FramebufferInfo< T >::Attachment", "struction_1_1gfx_1_1_framebuffer_info_1_1_attachment.html", null ],
    [ "ion::gfx::ArrayInfo< T >::Attribute", "struction_1_1gfx_1_1_array_info_1_1_attribute.html", null ],
    [ "ion::gfx::ProgramInfo< T >::Attribute", "struction_1_1gfx_1_1_program_info_1_1_attribute.html", null ],
    [ "ion::port::Barrier", "classion_1_1port_1_1_barrier.html", null ],
    [ "ion::analytics::Benchmark", "classion_1_1analytics_1_1_benchmark.html", null ],
    [ "ion::text::BinPacker", "classion_1_1text_1_1_bin_packer.html", null ],
    [ "ion::base::BoolType< b >", "struction_1_1base_1_1_bool_type.html", null ],
    [ "ion::base::BoolType< false >", "struction_1_1base_1_1_bool_type.html", [
      [ "ion::base::IsSameType< T, U >", "struction_1_1base_1_1_is_same_type.html", null ]
    ] ],
    [ "ion::base::BoolType< IsSameType< To, From >::value||IsBaseOf< To, From >::value >", "struction_1_1base_1_1_bool_type.html", [
      [ "ion::base::IsConvertible< From, To >", "struction_1_1base_1_1_is_convertible.html", null ]
    ] ],
    [ "ion::base::BoolType< true >", "struction_1_1base_1_1_bool_type.html", [
      [ "ion::base::IsSameType< T, T >", "struction_1_1base_1_1_is_same_type_3_01_t_00_01_t_01_4.html", null ]
    ] ],
    [ "ion::gfx::BufferObjectElement", "struction_1_1gfx_1_1_buffer_object_element.html", null ],
    [ "ion::gfx::BufferObject::BufferSubData", "struction_1_1gfx_1_1_buffer_object_1_1_buffer_sub_data.html", null ],
    [ "ion::gfxutils::BufferToAttributeBinder< T >", "classion_1_1gfxutils_1_1_buffer_to_attribute_binder.html", null ],
    [ "ion::gfx::ShaderInputRegistry::CombineFunction< T >", "struction_1_1gfx_1_1_shader_input_registry_1_1_combine_function.html", null ],
    [ "ion::base::ConditionalType< condition, A, B >", "struction_1_1base_1_1_conditional_type.html", null ],
    [ "ion::base::ConditionalType< false, A, B >", "struction_1_1base_1_1_conditional_type_3_01false_00_01_a_00_01_b_01_4.html", null ],
    [ "TimelineSearch::const_iterator", "class_timeline_search_1_1const__iterator.html", null ],
    [ "Timeline::const_iterator", "class_timeline_1_1const__iterator.html", null ],
    [ "ion::analytics::Benchmark::Constant", "struction_1_1analytics_1_1_benchmark_1_1_constant.html", null ],
    [ "ion::gfx::ResourceManager::DataRequest< InfoType >", "struction_1_1gfx_1_1_resource_manager_1_1_data_request.html", null ],
    [ "ion::gfx::ResourceManager::DataRequest< ion::gfx::ResourceManager::PlatformInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_data_request.html", null ],
    [ "ion::gfx::ResourceManager::DataRequest< ion::gfx::ResourceManager::TextureImageInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_data_request.html", null ],
    [ "ion::base::DateTime", "classion_1_1base_1_1_date_time.html", null ],
    [ "std::deque< T >", null, [
      [ "ion::base::AllocDeque< ion::gfx::ShaderInputRegistry::Spec >", "classion_1_1base_1_1_alloc_deque.html", null ],
      [ "ion::base::AllocDeque< Uniform >", "classion_1_1base_1_1_alloc_deque.html", null ],
      [ "ion::base::AllocDeque< T >", "classion_1_1base_1_1_alloc_deque.html", null ]
    ] ],
    [ "ion::analytics::Benchmark::Descriptor", "struction_1_1analytics_1_1_benchmark_1_1_descriptor.html", null ],
    [ "ion::base::internal_variant_utils::EmptyType< N >", "classion_1_1base_1_1internal__variant__utils_1_1_empty_type.html", null ],
    [ "ion::base::EnumHelper", "classion_1_1base_1_1_enum_helper.html", null ],
    [ "ion::gfx::TextureBase::Face", "classion_1_1gfx_1_1_texture_base_1_1_face.html", null ],
    [ "ion::base::internal_variant_utils::FalseType", "struction_1_1base_1_1internal__variant__utils_1_1_false_type.html", [
      [ "ion::base::internal_variant_utils::is_emptytype< T >", "struction_1_1base_1_1internal__variant__utils_1_1is__emptytype.html", null ]
    ] ],
    [ "ion::gfx::ResourceHolder::FieldBase", "classion_1_1gfx_1_1_resource_holder_1_1_field_base.html", [
      [ "ion::gfx::ResourceHolder::Field< std::string >", "classion_1_1gfx_1_1_resource_holder_1_1_field.html", null ],
      [ "ion::gfx::ResourceHolder::Field< T >", "classion_1_1gfx_1_1_resource_holder_1_1_field.html", [
        [ "ion::gfx::ResourceHolder::RangedField< T >", "classion_1_1gfx_1_1_resource_holder_1_1_ranged_field.html", null ]
      ] ],
      [ "ion::gfx::ResourceHolder::VectorField< T >", "classion_1_1gfx_1_1_resource_holder_1_1_vector_field.html", null ]
    ] ],
    [ "ion::math::FieldOfView< T >", "classion_1_1math_1_1_field_of_view.html", null ],
    [ "ion::text::Font::FontMetrics", "struction_1_1text_1_1_font_1_1_font_metrics.html", null ],
    [ "ion::text::FreeTypeFontTransformData", "struction_1_1text_1_1_free_type_font_transform_data.html", null ],
    [ "ion::base::FunctionCall< T >", "classion_1_1base_1_1_function_call.html", null ],
    [ "ion::gfx::ShaderInputRegistry::GenerateFunction< T >", "struction_1_1gfx_1_1_shader_input_registry_1_1_generate_function.html", null ],
    [ "ion::base::GenericLockGuardBase< MutexT >", "classion_1_1base_1_1_generic_lock_guard_base.html", [
      [ "ion::base::GenericLockGuard< MutexT >", "classion_1_1base_1_1_generic_lock_guard.html", null ],
      [ "ion::base::GenericTryLockGuard< MutexT >", "classion_1_1base_1_1_generic_try_lock_guard.html", null ]
    ] ],
    [ "ion::base::GenericLockGuardBase< port::Mutex >", "classion_1_1base_1_1_generic_lock_guard_base.html", [
      [ "ion::base::ManualLockGuard< T >", "classion_1_1base_1_1_manual_lock_guard.html", null ]
    ] ],
    [ "ion::base::GenericUnlockGuard< MutexT >", "classion_1_1base_1_1_generic_unlock_guard.html", null ],
    [ "ion::gfx::GraphicsManager::GlVersions", "struction_1_1gfx_1_1_graphics_manager_1_1_gl_versions.html", null ],
    [ "ion::text::Layout::Glyph", "struction_1_1text_1_1_layout_1_1_glyph.html", null ],
    [ "ion::text::Font::GlyphGrid", "struction_1_1text_1_1_font_1_1_glyph_grid.html", null ],
    [ "ion::text::FreeTypeFont::GlyphMetrics", "struction_1_1text_1_1_free_type_font_1_1_glyph_metrics.html", null ],
    [ "ion::analytics::GpuPerformanceTester", "classion_1_1analytics_1_1_gpu_performance_tester.html", null ],
    [ "ion::gfxprofile::GpuProfiler", "classion_1_1gfxprofile_1_1_gpu_profiler.html", null ],
    [ "ion::base::HasTrivialDestructor< T >", "struction_1_1base_1_1_has_trivial_destructor.html", null ],
    [ "ion::base::IsBaseOf< Base, Derived >::Helper", "struction_1_1base_1_1_is_base_of_1_1_helper.html", null ],
    [ "ion::remote::HttpClient", "classion_1_1remote_1_1_http_client.html", null ],
    [ "ion::remote::HttpServer", "classion_1_1remote_1_1_http_server.html", [
      [ "ion::remote::RemoteServer", "classion_1_1remote_1_1_remote_server.html", null ]
    ] ],
    [ "ion::text::FontImage::ImageData", "struction_1_1text_1_1_font_image_1_1_image_data.html", null ],
    [ "ion::base::IndexMap< OrderedIndexType, UnorderedIndexType >", "classion_1_1base_1_1_index_map.html", null ],
    [ "ion::base::IndexMap< EnumType, uint32 >", "classion_1_1base_1_1_index_map.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< T >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< InfoType >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::ArrayInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::BufferInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::FramebufferInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::ProgramInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::ResourceManager::PlatformInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::ResourceManager::TextureImageInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::SamplerInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::ShaderInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::gfx::ResourceManager::InfoCallback< ion::gfx::TextureInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_info_callback.html", null ],
    [ "ion::analytics::IntervalDiscrepancy", "struction_1_1analytics_1_1_interval_discrepancy.html", null ],
    [ "ion::base::IsBaseOf< Base, Derived >", "struction_1_1base_1_1_is_base_of.html", null ],
    [ "ion::base::internal::IsSameOrDerivedFrom< T, Base >", "struction_1_1base_1_1internal_1_1_is_same_or_derived_from.html", null ],
    [ "ion::text::Layout", "classion_1_1text_1_1_layout.html", null ],
    [ "ion::text::LayoutOptions", "struction_1_1text_1_1_layout_options.html", null ],
    [ "ion::base::Lazy< T >", "classion_1_1base_1_1_lazy.html", null ],
    [ "ion::base::SettingBase::ListenerInfo", "struction_1_1base_1_1_setting_base_1_1_listener_info.html", null ],
    [ "ion::port::android::LocalFrame", "classion_1_1port_1_1android_1_1_local_frame.html", null ],
    [ "ion::port::LogEntryWriter", "classion_1_1port_1_1_log_entry_writer.html", [
      [ "ion::base::LogChecker", "classion_1_1base_1_1_log_checker.html", null ],
      [ "ion::base::NullLogEntryWriter", "classion_1_1base_1_1_null_log_entry_writer.html", null ]
    ] ],
    [ "ion::base::logging_internal::Logger", "classion_1_1base_1_1logging__internal_1_1_logger.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< Type >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< float >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< GLfloat >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< GLint >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< GraphicsManager::ShaderPrecision >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< int >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 10 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 11 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 12 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 13 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 14 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 15 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 16 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 17 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 18 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 19 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 20 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 21 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 22 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 23 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 24 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 25 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 26 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 27 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 28 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 29 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 30 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 31 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 32 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 33 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 34 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 35 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 36 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 37 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 38 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 39 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 40 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 7 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 8 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< internal_variant_utils::EmptyType< 9 > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::Matrix2f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::Matrix3f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::Matrix4f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::Range1f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::Range1i >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase2f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase2i >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase2ui >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase3f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase3i >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase3ui >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase4f >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase4i >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< math::VectorBase4ui >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< std::vector< GLint > >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T1 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T10 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T11 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T12 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T13 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T14 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T15 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T16 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T17 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T18 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T19 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T2 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T20 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T21 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T22 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T23 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T24 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T25 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T26 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T27 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T28 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T29 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T3 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T30 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T31 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T32 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T33 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T34 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T35 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T36 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T37 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T38 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T39 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T4 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T40 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T5 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T6 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T7 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T8 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< T9 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "ion::base::internal_variant_utils::ManualConstructor< uint32 >", "classion_1_1base_1_1internal__variant__utils_1_1_manual_constructor.html", null ],
    [ "std::map< K, T >", null, [
      [ "ion::base::AllocMap< const std::string, SpecMapEntry >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< const void *, size_t >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< CTFontRef, uint16 >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< GlyphIndex, GlyphGrid >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< GlyphIndex, GlyphMetaData >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< GlyphIndex, math::Range2f >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< std::string, Callback >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< std::string, FileInfo >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< std::string, FontImagePtr >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< std::string, FontPtr >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< std::string, ProgramInfo >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< std::string, unsigned int >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< uint16, CTFontRef >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< uint32, uint32 >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< unsigned int, std::string >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< void *, size_t >", "classion_1_1base_1_1_alloc_map.html", null ],
      [ "ion::base::AllocMap< K, V, Compare >", "classion_1_1base_1_1_alloc_map.html", null ]
    ] ],
    [ "ion::math::Matrix< Dimension, T >", "classion_1_1math_1_1_matrix.html", null ],
    [ "ion::analytics::GpuPerformanceTester::Measurement", "struction_1_1analytics_1_1_gpu_performance_tester_1_1_measurement.html", null ],
    [ "ion::port::MemoryMappedFile", "classion_1_1port_1_1_memory_mapped_file.html", null ],
    [ "ion::port::Mutex", "classion_1_1port_1_1_mutex.html", null ],
    [ "ion::base::logging_internal::NullLogger", "classion_1_1base_1_1logging__internal_1_1_null_logger.html", null ],
    [ "ion::base::OnceFlag", "classion_1_1base_1_1_once_flag.html", null ],
    [ "ion::gfx::Image::PixelFormat", "struction_1_1gfx_1_1_image_1_1_pixel_format.html", null ],
    [ "ion::gfx::ResourceManager::PlatformInfo", "struction_1_1gfx_1_1_resource_manager_1_1_platform_info.html", null ],
    [ "ion::gfxutils::Printer", "classion_1_1gfxutils_1_1_printer.html", null ],
    [ "ion::text::Layout::Quad", "struction_1_1text_1_1_layout_1_1_quad.html", null ],
    [ "ion::base::DateTime::Range", "classion_1_1base_1_1_date_time_1_1_range.html", null ],
    [ "ion::math::Range1TWrapper< T, N >", "struction_1_1math_1_1_range1_t_wrapper.html", null ],
    [ "ion::math::RangeBase< Dimension, T >", "classion_1_1math_1_1_range_base.html", [
      [ "ion::math::Range< Dimension, T >", "classion_1_1math_1_1_range.html", null ]
    ] ],
    [ "ion::math::RangeBase< 1, T >", "classion_1_1math_1_1_range_base_3_011_00_01_t_01_4.html", null ],
    [ "ion::base::ReadLock", "classion_1_1base_1_1_read_lock.html", null ],
    [ "ion::base::ReadWriteLock", "classion_1_1base_1_1_read_write_lock.html", null ],
    [ "ion::base::StlInlinedAllocator< T, N >::rebind< U >", "struction_1_1base_1_1_stl_inlined_allocator_1_1rebind.html", null ],
    [ "ion::base::StlAllocator< T >::rebind< U >", "struction_1_1base_1_1_stl_allocator_1_1rebind.html", null ],
    [ "ion::base::StlInlinedAllocator< T, N >::RebindHelper< U, V >", "struction_1_1base_1_1_stl_inlined_allocator_1_1_rebind_helper.html", null ],
    [ "ion::base::StlInlinedAllocator< T, N >::RebindHelper< U, U >", "struction_1_1base_1_1_stl_inlined_allocator_1_1_rebind_helper_3_01_u_00_01_u_01_4.html", null ],
    [ "ion::text::BinPacker::Rectangle", "struction_1_1text_1_1_bin_packer_1_1_rectangle.html", null ],
    [ "ion::base::ReferentPtr< T >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< AttributeArray >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< BufferObject >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< CubeMapTexture >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< DataContainer >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Font >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< FontImage >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Frame >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< GraphicsManager >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< HolderType >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Image >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< IndexBuffer >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::base::WeakReferent::Proxy >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::AttributeArray >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::BufferObject >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::FramebufferObject >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::Sampler >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::Shader >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::ShaderProgram >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ion::gfx::TextureBase >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Node >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< NodeGraphHandler >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Renderer >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ResourceCallback< T > >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Sampler >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ShaderInputRegistry >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ShaderManager >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ShaderProgram >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< ShaderSourceComposer >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< StateTable >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Texture >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< TextureBase >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::ReferentPtr< Websocket >", "struction_1_1base_1_1_referent_ptr.html", null ],
    [ "ion::base::internal::ResolverHelper< VariantType, TypeToResolve, Base >", "struction_1_1base_1_1internal_1_1_resolver_helper.html", null ],
    [ "ion::gfx::ResourceBase", "classion_1_1gfx_1_1_resource_base.html", null ],
    [ "ResourceInfo", null, [
      [ "ion::gfx::RenderbufferInfo< ResourceInfo >", "struction_1_1gfx_1_1_renderbuffer_info.html", null ]
    ] ],
    [ "ion::gfx::ResourceManager::ResourceInfo", "struction_1_1gfx_1_1_resource_manager_1_1_resource_info.html", [
      [ "ion::gfx::ResourceManager::ArrayResourceInfo", "struction_1_1gfx_1_1_resource_manager_1_1_array_resource_info.html", null ],
      [ "ion::gfx::ResourceManager::BufferTargetInfo", "struction_1_1gfx_1_1_resource_manager_1_1_buffer_target_info.html", null ],
      [ "ion::gfx::ResourceManager::FramebufferResourceInfo", "struction_1_1gfx_1_1_resource_manager_1_1_framebuffer_resource_info.html", null ],
      [ "ion::gfx::ResourceManager::TextureResourceInfo", "struction_1_1gfx_1_1_resource_manager_1_1_texture_resource_info.html", null ]
    ] ],
    [ "ion::gfx::ResourceManager::ResourceRequest< HolderType, InfoType >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::AttributeArray, ion::gfx::ArrayInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::BufferObject, ion::gfx::BufferInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::FramebufferObject, ion::gfx::FramebufferInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::Sampler, ion::gfx::SamplerInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::Shader, ion::gfx::ShaderInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::ShaderProgram, ion::gfx::ProgramInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::gfx::ResourceManager::ResourceRequest< ion::gfx::TextureBase, ion::gfx::TextureInfo >", "struction_1_1gfx_1_1_resource_manager_1_1_resource_request.html", null ],
    [ "ion::remote::HttpClient::Response", "struction_1_1remote_1_1_http_client_1_1_response.html", null ],
    [ "ion::math::Rotation< T >", "classion_1_1math_1_1_rotation.html", null ],
    [ "ion::analytics::Benchmark::Sample", "struction_1_1analytics_1_1_benchmark_1_1_sample.html", null ],
    [ "ion::analytics::Benchmark::SampledVariable", "struction_1_1analytics_1_1_benchmark_1_1_sampled_variable.html", null ],
    [ "ion::analytics::SampleMapping", "classion_1_1analytics_1_1_sample_mapping.html", null ],
    [ "ion::base::ScopedAllocation< T >", "classion_1_1base_1_1_scoped_allocation.html", null ],
    [ "ion::profile::ScopedFrameTracer", "classion_1_1profile_1_1_scoped_frame_tracer.html", null ],
    [ "ion::gfxprofile::ScopedGlTracer", "classion_1_1gfxprofile_1_1_scoped_gl_tracer.html", null ],
    [ "ion::port::android::ScopedJObject", "classion_1_1port_1_1android_1_1_scoped_j_object.html", null ],
    [ "ion::base::ScopedSettingValue< T >", "classion_1_1base_1_1_scoped_setting_value.html", null ],
    [ "ion::port::android::ScopedTrace", "classion_1_1port_1_1android_1_1_scoped_trace.html", null ],
    [ "ion::profile::ScopedTracer", "classion_1_1profile_1_1_scoped_tracer.html", null ],
    [ "ion::port::Semaphore", "classion_1_1port_1_1_semaphore.html", null ],
    [ "Sequence", "class_sequence.html", null ],
    [ "std::set< K >", null, [
      [ "ion::base::AllocSet< GlyphIndex >", "classion_1_1base_1_1_alloc_set.html", null ],
      [ "ion::base::AllocSet< ion::port::ThreadId >", "classion_1_1base_1_1_alloc_set.html", null ],
      [ "ion::base::AllocSet< ShaderProgramResource * >", "classion_1_1base_1_1_alloc_set.html", null ],
      [ "ion::base::AllocSet< std::string >", "classion_1_1base_1_1_alloc_set.html", null ],
      [ "ion::base::AllocSet< T, Compare >", "classion_1_1base_1_1_alloc_set.html", null ]
    ] ],
    [ "ion::base::SettingBase", "classion_1_1base_1_1_setting_base.html", [
      [ "ion::base::Setting< T >", "classion_1_1base_1_1_setting.html", [
        [ "ion::base::EnvironmentSetting< T >", "classion_1_1base_1_1_environment_setting.html", null ]
      ] ],
      [ "ion::base::Setting< std::atomic< T > >", "classion_1_1base_1_1_setting_3_01std_1_1atomic_3_01_t_01_4_01_4.html", null ],
      [ "ion::base::Setting< bool >", "classion_1_1base_1_1_setting.html", null ]
    ] ],
    [ "ion::base::SettingGroup", "classion_1_1base_1_1_setting_group.html", null ],
    [ "ion::base::SettingManager", "classion_1_1base_1_1_setting_manager.html", null ],
    [ "ion::gfx::ShaderInputBase", "classion_1_1gfx_1_1_shader_input_base.html", [
      [ "ion::gfx::ShaderInput< ValueHolderType, ValueEnumType >", "classion_1_1gfx_1_1_shader_input.html", null ],
      [ "ion::gfx::ShaderInput< AttributeValueType, AttributeType >", "classion_1_1gfx_1_1_shader_input.html", [
        [ "ion::gfx::Attribute", "classion_1_1gfx_1_1_attribute.html", null ]
      ] ],
      [ "ion::gfx::ShaderInput< UniformValueType, UniformType >", "classion_1_1gfx_1_1_shader_input.html", [
        [ "ion::gfx::Uniform", "classion_1_1gfx_1_1_uniform.html", null ]
      ] ]
    ] ],
    [ "ion::gfx::GraphicsManager::ShaderPrecision", "struction_1_1gfx_1_1_graphics_manager_1_1_shader_precision.html", null ],
    [ "ion::gfxutils::ShapeSpec", "struction_1_1gfxutils_1_1_shape_spec.html", [
      [ "ion::gfxutils::BoxSpec", "struction_1_1gfxutils_1_1_box_spec.html", null ],
      [ "ion::gfxutils::CylinderSpec", "struction_1_1gfxutils_1_1_cylinder_spec.html", null ],
      [ "ion::gfxutils::EllipsoidSpec", "struction_1_1gfxutils_1_1_ellipsoid_spec.html", null ],
      [ "ion::gfxutils::ExternalShapeSpec", "struction_1_1gfxutils_1_1_external_shape_spec.html", null ],
      [ "ion::gfxutils::PlanarShapeSpec", "struction_1_1gfxutils_1_1_planar_shape_spec.html", [
        [ "ion::gfxutils::RectangleSpec", "struction_1_1gfxutils_1_1_rectangle_spec.html", null ],
        [ "ion::gfxutils::RegularPolygonSpec", "struction_1_1gfxutils_1_1_regular_polygon_spec.html", null ]
      ] ]
    ] ],
    [ "ion::base::Shareable", "classion_1_1base_1_1_shareable.html", [
      [ "ion::base::AllocationTracker", "classion_1_1base_1_1_allocation_tracker.html", [
        [ "ion::base::AllocationSizeTracker", "classion_1_1base_1_1_allocation_size_tracker.html", null ],
        [ "ion::base::FullAllocationTracker", "classion_1_1base_1_1_full_allocation_tracker.html", null ]
      ] ],
      [ "ion::base::Allocator", "classion_1_1base_1_1_allocator.html", null ],
      [ "ion::base::Referent", "classion_1_1base_1_1_referent.html", null ],
      [ "ion::base::StaticDeleterDeleter", "classion_1_1base_1_1_static_deleter_deleter.html", null ]
    ] ],
    [ "ion::base::SharedPtr< T >", "classion_1_1base_1_1_shared_ptr.html", null ],
    [ "ion::base::SharedPtr< AllocationTracker >", "classion_1_1base_1_1_shared_ptr.html", null ],
    [ "ion::base::SharedPtr< Allocator >", "classion_1_1base_1_1_shared_ptr.html", null ],
    [ "ion::base::SharedPtr< InternalAllocator >", "classion_1_1base_1_1_shared_ptr.html", null ],
    [ "ion::base::SharedPtr< ion::base::Shareable >", "classion_1_1base_1_1_shared_ptr.html", null ],
    [ "ion::base::SharedPtr< SettingData >", "classion_1_1base_1_1_shared_ptr.html", null ],
    [ "ion::base::logging_internal::SingleLogger", "classion_1_1base_1_1logging__internal_1_1_single_logger.html", null ],
    [ "ion::gfx::BufferObject::Spec", "struction_1_1gfx_1_1_buffer_object_1_1_spec.html", null ],
    [ "ion::gfx::ShaderInputRegistry::Spec< T >", "struction_1_1gfx_1_1_shader_input_registry_1_1_spec.html", null ],
    [ "ion::base::SpinMutex", "classion_1_1base_1_1_spin_mutex.html", null ],
    [ "ion::port::StackTrace", "classion_1_1port_1_1_stack_trace.html", null ],
    [ "ion::base::StaticDeleterBase", "classion_1_1base_1_1_static_deleter_base.html", [
      [ "ion::base::StaticDeleter< T >", "classion_1_1base_1_1_static_deleter.html", null ],
      [ "ion::base::StaticDeleter< T[]>", "classion_1_1base_1_1_static_deleter_3_01_t[]_4.html", null ]
    ] ],
    [ "ion::math::VectorBase< Dimension, T >::StaticHelper< Dim, U >", "struction_1_1math_1_1_vector_base_1_1_static_helper.html", null ],
    [ "ion::math::VectorBase< Dimension, T >::StaticHelper< 1, U >", "struction_1_1math_1_1_vector_base_1_1_static_helper_3_011_00_01_u_01_4.html", null ],
    [ "ion::math::VectorBase< Dimension, T >::StaticHelper< 2, U >", "struction_1_1math_1_1_vector_base_1_1_static_helper_3_012_00_01_u_01_4.html", null ],
    [ "ion::math::VectorBase< Dimension, T >::StaticHelper< 3, U >", "struction_1_1math_1_1_vector_base_1_1_static_helper_3_013_00_01_u_01_4.html", null ],
    [ "ion::math::VectorBase< Dimension, T >::StaticHelper< 4, U >", "struction_1_1math_1_1_vector_base_1_1_static_helper_3_014_00_01_u_01_4.html", null ],
    [ "ion::gfx::TextureBase::SubImage", "struction_1_1gfx_1_1_texture_base_1_1_sub_image.html", null ],
    [ "T", "class_t.html", [
      [ "ion::gfx::ArrayInfo< T >", "struction_1_1gfx_1_1_array_info.html", null ],
      [ "ion::gfx::BufferInfo< T >", "struction_1_1gfx_1_1_buffer_info.html", null ],
      [ "ion::gfx::FramebufferInfo< T >", "struction_1_1gfx_1_1_framebuffer_info.html", null ],
      [ "ion::gfx::ProgramInfo< T >", "struction_1_1gfx_1_1_program_info.html", null ],
      [ "ion::gfx::RenderbufferInfo< T >", "struction_1_1gfx_1_1_renderbuffer_info.html", null ],
      [ "ion::gfx::SamplerInfo< T >", "struction_1_1gfx_1_1_sampler_info.html", null ],
      [ "ion::gfx::ShaderInfo< T >", "struction_1_1gfx_1_1_shader_info.html", null ],
      [ "ion::gfx::SyncInfo< T >", "struction_1_1gfx_1_1_sync_info.html", null ],
      [ "ion::gfx::TextureInfo< T >", "struction_1_1gfx_1_1_texture_info.html", null ],
      [ "ion::gfx::TimerInfo< T >", "struction_1_1gfx_1_1_timer_info.html", null ],
      [ "ion::gfx::TransformFeedbackInfo< T >", "struction_1_1gfx_1_1_transform_feedback_info.html", null ]
    ] ],
    [ "ion::text::TextSize", "struction_1_1text_1_1_text_size.html", null ],
    [ "ion::gfx::ResourceManager::TextureImageInfo", "struction_1_1gfx_1_1_resource_manager_1_1_texture_image_info.html", null ],
    [ "ion::base::ThreadLocalObject< T >", "classion_1_1base_1_1_thread_local_object.html", null ],
    [ "ion::base::ThreadLocalObject< ion::profile::TraceRecorder * >", "classion_1_1base_1_1_thread_local_object.html", null ],
    [ "ion::base::ThreadLocalObject< NamedTraceRecorderArray >", "classion_1_1base_1_1_thread_local_object.html", null ],
    [ "ion::base::ThreadSpawner", "classion_1_1base_1_1_thread_spawner.html", null ],
    [ "ion::base::logging_internal::ThrottledLogger", "classion_1_1base_1_1logging__internal_1_1_throttled_logger.html", null ],
    [ "Timeline", "class_timeline.html", null ],
    [ "ion::profile::TimelineMetric", "classion_1_1profile_1_1_timeline_metric.html", null ],
    [ "TimelineNode", "class_timeline_node.html", [
      [ "TimelineEvent", "class_timeline_event.html", [
        [ "TimelineFrame", "class_timeline_frame.html", null ],
        [ "TimelineRange", "class_timeline_range.html", null ],
        [ "TimelineScope", "class_timeline_scope.html", null ]
      ] ],
      [ "TimelineThread", "class_timeline_thread.html", null ]
    ] ],
    [ "TimelineSearch", "class_timeline_search.html", null ],
    [ "ion::port::Timer", "classion_1_1port_1_1_timer.html", null ],
    [ "ion::gfx::TraceCallExtractor", "classion_1_1gfx_1_1_trace_call_extractor.html", null ],
    [ "ion::profile::TraceRecorder::TraceHeader", "struction_1_1profile_1_1_trace_recorder_1_1_trace_header.html", null ],
    [ "ion::port::android::Tracer", "classion_1_1port_1_1android_1_1_tracer.html", null ],
    [ "ion::gfx::TracingHelper", "classion_1_1gfx_1_1_tracing_helper.html", null ],
    [ "ion::base::internal_variant_utils::TrueType", "struction_1_1base_1_1internal__variant__utils_1_1_true_type.html", [
      [ "ion::base::internal_variant_utils::is_emptytype< EmptyType< N > >", "struction_1_1base_1_1internal__variant__utils_1_1is__emptytype_3_01_empty_type_3_01_n_01_4_01_4.html", null ]
    ] ],
    [ "ion::gfx::ProgramInfo< T >::Uniform", "struction_1_1gfx_1_1_program_info_1_1_uniform.html", null ],
    [ "ion::gfx::UniformHolder", "classion_1_1gfx_1_1_uniform_holder.html", [
      [ "ion::gfx::Node", "classion_1_1gfx_1_1_node.html", null ],
      [ "ion::gfx::UniformBlock", "classion_1_1gfx_1_1_uniform_block.html", null ]
    ] ],
    [ "std::unordered_map< K, T >", null, [
      [ "ion::base::AllocUnorderedMap< const ShaderInputRegistry::AttributeSpec *, GLint >", "classion_1_1base_1_1_alloc_unordered_map.html", null ],
      [ "ion::base::AllocUnorderedMap< const void *, uint32 >", "classion_1_1base_1_1_alloc_unordered_map.html", null ],
      [ "ion::base::AllocUnorderedMap< TextureResource *, GLuint >", "classion_1_1base_1_1_alloc_unordered_map.html", null ],
      [ "ion::base::AllocUnorderedMap< uint32, const char * >", "classion_1_1base_1_1_alloc_unordered_map.html", null ],
      [ "ion::base::AllocUnorderedMap< Key, Value, Hash, Pred >", "classion_1_1base_1_1_alloc_unordered_map.html", null ]
    ] ],
    [ "std::unordered_set< K >", null, [
      [ "ion::base::AllocUnorderedSet< Value, Hash, Pred >", "classion_1_1base_1_1_alloc_unordered_set.html", null ]
    ] ],
    [ "ion::remote::HttpClient::Url", "struction_1_1remote_1_1_http_client_1_1_url.html", null ],
    [ "ion::base::Utf8Iterator", "classion_1_1base_1_1_utf8_iterator.html", null ],
    [ "ion::analytics::Benchmark::VariableAccumulator", "classion_1_1analytics_1_1_benchmark_1_1_variable_accumulator.html", null ],
    [ "ion::analytics::Benchmark::VariableSampler", "classion_1_1analytics_1_1_benchmark_1_1_variable_sampler.html", null ],
    [ "ion::base::Variant< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40 >", "classion_1_1base_1_1_variant.html", null ],
    [ "ion::base::Variant< GLint, GLfloat, math::Range1f, math::Range1i, GraphicsManager::ShaderPrecision, std::vector< GLint > >", "classion_1_1base_1_1_variant.html", null ],
    [ "ion::base::Variant< int, uint32, float, math::VectorBase2f, math::VectorBase3f, math::VectorBase4f, math::VectorBase2i, math::VectorBase3i, math::VectorBase4i, math::VectorBase2ui, math::VectorBase3ui, math::VectorBase4ui, math::Matrix2f, math::Matrix3f, math::Matrix4f >", "classion_1_1base_1_1_variant.html", null ],
    [ "ion::base::VariantTypeResolver< VariantType, TypeToResolve >", "struction_1_1base_1_1_variant_type_resolver.html", null ],
    [ "ion::gfx::ProgramInfo< T >::Varying", "struction_1_1gfx_1_1_program_info_1_1_varying.html", null ],
    [ "std::vector< T >", null, [
      [ "ion::base::AllocVector< Allocation >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< AtomicSizeT >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< BufferAttributeInfo >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< const Uniform * >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< DeferredUpdate >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< double >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< Entry >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< FunctionGroup >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< GLuint >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ImageDataWrapper >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ImageUnit >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< Index >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< int >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::base::SharedPtr >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::gfx::Attribute >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::gfx::BufferObject::BufferSubData >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::gfx::BufferObject::Spec >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::gfx::ResourceHolder::FieldBase * >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::gfx::TextureBase::ion::gfx::TextureBase::SubImage >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< ion::gfx::Uniform >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< NotifierPtr >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< Resource * >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< StateTablePtr >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< std::unique_ptr< ion::base::FunctionCallBase > >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< std::unique_ptr< UniformStack > >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< TraceRecorder * >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< uint32 >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< uint8 >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< UniformCacheEntry >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< VertexRange >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::AllocVector< WrapperBase * >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::InlinedAllocVector< ion::base::AllocUnorderedMap, 1 >", "classion_1_1base_1_1_inlined_alloc_vector.html", null ],
      [ "ion::base::AllocVector< T >", "classion_1_1base_1_1_alloc_vector.html", null ],
      [ "ion::base::InlinedAllocVector< T, N >", "classion_1_1base_1_1_inlined_alloc_vector.html", null ]
    ] ],
    [ "ion::math::VectorBase< Dimension, T >", "classion_1_1math_1_1_vector_base.html", [
      [ "ion::math::Point< Dimension, T >", "classion_1_1math_1_1_point.html", null ],
      [ "ion::math::Vector< Dimension, T >", "classion_1_1math_1_1_vector.html", null ],
      [ "ion::math::Vector< 4, T >", "classion_1_1math_1_1_vector.html", null ]
    ] ],
    [ "ion::portgfx::Visual", "classion_1_1portgfx_1_1_visual.html", null ],
    [ "ion::profile::VSyncProfiler", "classion_1_1profile_1_1_v_sync_profiler.html", null ],
    [ "ion::base::WeakReferentPtr< T >", "classion_1_1base_1_1_weak_referent_ptr.html", null ],
    [ "ion::base::WeakReferentPtr< FramebufferObject >", "classion_1_1base_1_1_weak_referent_ptr.html", null ],
    [ "ion::base::WorkerPool::Worker", "classion_1_1base_1_1_worker_pool_1_1_worker.html", null ],
    [ "ion::base::WriteLock", "classion_1_1base_1_1_write_lock.html", null ],
    [ "ion::base::ZipAssetManager", "classion_1_1base_1_1_zip_asset_manager.html", null ],
    [ "AttributeType", "class_attribute_type.html", null ],
    [ "bool", "classbool.html", null ],
    [ "Key", "class_key.html", null ],
    [ "size_t", "classsize__t.html", null ],
    [ "uint64", "classuint64.html", null ],
    [ "UniformType", "class_uniform_type.html", null ],
    [ "V", "class_v.html", null ],
    [ "Value", "class_value.html", null ]
];