var namespaceion_1_1base =
[
    [ "AllocTracker", "namespaceion_1_1base_1_1_alloc_tracker.html", null ],
    [ "internal", "namespaceion_1_1base_1_1internal.html", "namespaceion_1_1base_1_1internal" ],
    [ "internal_variant_utils", "namespaceion_1_1base_1_1internal__variant__utils.html", "namespaceion_1_1base_1_1internal__variant__utils" ],
    [ "logging_internal", "namespaceion_1_1base_1_1logging__internal.html", "namespaceion_1_1base_1_1logging__internal" ],
    [ "Allocatable", "classion_1_1base_1_1_allocatable.html", "classion_1_1base_1_1_allocatable" ],
    [ "AllocationManager", "classion_1_1base_1_1_allocation_manager.html", "classion_1_1base_1_1_allocation_manager" ],
    [ "AllocationSizeTracker", "classion_1_1base_1_1_allocation_size_tracker.html", "classion_1_1base_1_1_allocation_size_tracker" ],
    [ "AllocationTracker", "classion_1_1base_1_1_allocation_tracker.html", "classion_1_1base_1_1_allocation_tracker" ],
    [ "Allocator", "classion_1_1base_1_1_allocator.html", "classion_1_1base_1_1_allocator" ],
    [ "Array2", "classion_1_1base_1_1_array2.html", "classion_1_1base_1_1_array2" ],
    [ "CallList", "classion_1_1base_1_1_call_list.html", "classion_1_1base_1_1_call_list" ],
    [ "CircularBuffer", "classion_1_1base_1_1_circular_buffer.html", "classion_1_1base_1_1_circular_buffer" ],
    [ "DataContainer", "classion_1_1base_1_1_data_container.html", "classion_1_1base_1_1_data_container" ],
    [ "DateTime", "classion_1_1base_1_1_date_time.html", "classion_1_1base_1_1_date_time" ],
    [ "EnumHelper", "classion_1_1base_1_1_enum_helper.html", "classion_1_1base_1_1_enum_helper" ],
    [ "FullAllocationTracker", "classion_1_1base_1_1_full_allocation_tracker.html", "classion_1_1base_1_1_full_allocation_tracker" ],
    [ "FunctionCallBase", "classion_1_1base_1_1_function_call_base.html", "classion_1_1base_1_1_function_call_base" ],
    [ "FunctionCall", "classion_1_1base_1_1_function_call.html", null ],
    [ "FunctionCall< ReturnType(Types...)>", "classion_1_1base_1_1_function_call_3_01_return_type_07_types_8_8_8_08_4.html", "classion_1_1base_1_1_function_call_3_01_return_type_07_types_8_8_8_08_4" ],
    [ "IndexMap", "classion_1_1base_1_1_index_map.html", "classion_1_1base_1_1_index_map" ],
    [ "GenericLockGuardBase", "classion_1_1base_1_1_generic_lock_guard_base.html", "classion_1_1base_1_1_generic_lock_guard_base" ],
    [ "GenericLockGuard", "classion_1_1base_1_1_generic_lock_guard.html", "classion_1_1base_1_1_generic_lock_guard" ],
    [ "GenericTryLockGuard", "classion_1_1base_1_1_generic_try_lock_guard.html", "classion_1_1base_1_1_generic_try_lock_guard" ],
    [ "GenericUnlockGuard", "classion_1_1base_1_1_generic_unlock_guard.html", "classion_1_1base_1_1_generic_unlock_guard" ],
    [ "ManualLockGuard", "classion_1_1base_1_1_manual_lock_guard.html", "classion_1_1base_1_1_manual_lock_guard" ],
    [ "LogChecker", "classion_1_1base_1_1_log_checker.html", "classion_1_1base_1_1_log_checker" ],
    [ "MemoryZipStream", "classion_1_1base_1_1_memory_zip_stream.html", "classion_1_1base_1_1_memory_zip_stream" ],
    [ "Notifier", "classion_1_1base_1_1_notifier.html", "classion_1_1base_1_1_notifier" ],
    [ "NullLogEntryWriter", "classion_1_1base_1_1_null_log_entry_writer.html", "classion_1_1base_1_1_null_log_entry_writer" ],
    [ "OnceFlag", "classion_1_1base_1_1_once_flag.html", "classion_1_1base_1_1_once_flag" ],
    [ "Lazy", "classion_1_1base_1_1_lazy.html", "classion_1_1base_1_1_lazy" ],
    [ "ReadWriteLock", "classion_1_1base_1_1_read_write_lock.html", "classion_1_1base_1_1_read_write_lock" ],
    [ "ReadLock", "classion_1_1base_1_1_read_lock.html", "classion_1_1base_1_1_read_lock" ],
    [ "WriteLock", "classion_1_1base_1_1_write_lock.html", "classion_1_1base_1_1_write_lock" ],
    [ "Referent", "classion_1_1base_1_1_referent.html", "classion_1_1base_1_1_referent" ],
    [ "ReferentPtr", "struction_1_1base_1_1_referent_ptr.html", "struction_1_1base_1_1_referent_ptr" ],
    [ "ScopedAllocation", "classion_1_1base_1_1_scoped_allocation.html", "classion_1_1base_1_1_scoped_allocation" ],
    [ "SettingBase", "classion_1_1base_1_1_setting_base.html", "classion_1_1base_1_1_setting_base" ],
    [ "SettingGroup", "classion_1_1base_1_1_setting_group.html", "classion_1_1base_1_1_setting_group" ],
    [ "Setting", "classion_1_1base_1_1_setting.html", "classion_1_1base_1_1_setting" ],
    [ "Setting< std::atomic< T > >", "classion_1_1base_1_1_setting_3_01std_1_1atomic_3_01_t_01_4_01_4.html", "classion_1_1base_1_1_setting_3_01std_1_1atomic_3_01_t_01_4_01_4" ],
    [ "EnvironmentSetting", "classion_1_1base_1_1_environment_setting.html", "classion_1_1base_1_1_environment_setting" ],
    [ "ScopedSettingValue", "classion_1_1base_1_1_scoped_setting_value.html", "classion_1_1base_1_1_scoped_setting_value" ],
    [ "SettingManager", "classion_1_1base_1_1_setting_manager.html", "classion_1_1base_1_1_setting_manager" ],
    [ "Shareable", "classion_1_1base_1_1_shareable.html", "classion_1_1base_1_1_shareable" ],
    [ "SharedPtr", "classion_1_1base_1_1_shared_ptr.html", "classion_1_1base_1_1_shared_ptr" ],
    [ "SpinMutex", "classion_1_1base_1_1_spin_mutex.html", "classion_1_1base_1_1_spin_mutex" ],
    [ "StaticDeleterBase", "classion_1_1base_1_1_static_deleter_base.html", "classion_1_1base_1_1_static_deleter_base" ],
    [ "StaticDeleter", "classion_1_1base_1_1_static_deleter.html", "classion_1_1base_1_1_static_deleter" ],
    [ "StaticDeleter< T[]>", "classion_1_1base_1_1_static_deleter_3_01_t[]_4.html", "classion_1_1base_1_1_static_deleter_3_01_t[]_4" ],
    [ "StaticDeleterDeleter", "classion_1_1base_1_1_static_deleter_deleter.html", "classion_1_1base_1_1_static_deleter_deleter" ],
    [ "AllocDeque", "classion_1_1base_1_1_alloc_deque.html", "classion_1_1base_1_1_alloc_deque" ],
    [ "AllocMap", "classion_1_1base_1_1_alloc_map.html", "classion_1_1base_1_1_alloc_map" ],
    [ "AllocSet", "classion_1_1base_1_1_alloc_set.html", "classion_1_1base_1_1_alloc_set" ],
    [ "AllocUnorderedMap", "classion_1_1base_1_1_alloc_unordered_map.html", "classion_1_1base_1_1_alloc_unordered_map" ],
    [ "AllocUnorderedSet", "classion_1_1base_1_1_alloc_unordered_set.html", "classion_1_1base_1_1_alloc_unordered_set" ],
    [ "AllocVector", "classion_1_1base_1_1_alloc_vector.html", "classion_1_1base_1_1_alloc_vector" ],
    [ "InlinedAllocVector", "classion_1_1base_1_1_inlined_alloc_vector.html", "classion_1_1base_1_1_inlined_alloc_vector" ],
    [ "StlAllocator", "classion_1_1base_1_1_stl_allocator.html", "classion_1_1base_1_1_stl_allocator" ],
    [ "StlInlinedAllocator", "classion_1_1base_1_1_stl_inlined_allocator.html", "classion_1_1base_1_1_stl_inlined_allocator" ],
    [ "ThreadLocalObject", "classion_1_1base_1_1_thread_local_object.html", "classion_1_1base_1_1_thread_local_object" ],
    [ "ThreadSpawner", "classion_1_1base_1_1_thread_spawner.html", "classion_1_1base_1_1_thread_spawner" ],
    [ "BoolType", "struction_1_1base_1_1_bool_type.html", null ],
    [ "IsSameType", "struction_1_1base_1_1_is_same_type.html", null ],
    [ "IsSameType< T, T >", "struction_1_1base_1_1_is_same_type_3_01_t_00_01_t_01_4.html", null ],
    [ "IsBaseOf", "struction_1_1base_1_1_is_base_of.html", "struction_1_1base_1_1_is_base_of" ],
    [ "IsConvertible", "struction_1_1base_1_1_is_convertible.html", null ],
    [ "ConditionalType", "struction_1_1base_1_1_conditional_type.html", "struction_1_1base_1_1_conditional_type" ],
    [ "ConditionalType< false, A, B >", "struction_1_1base_1_1_conditional_type_3_01false_00_01_a_00_01_b_01_4.html", "struction_1_1base_1_1_conditional_type_3_01false_00_01_a_00_01_b_01_4" ],
    [ "HasTrivialDestructor", "struction_1_1base_1_1_has_trivial_destructor.html", null ],
    [ "Utf8Iterator", "classion_1_1base_1_1_utf8_iterator.html", "classion_1_1base_1_1_utf8_iterator" ],
    [ "Variant", "classion_1_1base_1_1_variant.html", "classion_1_1base_1_1_variant" ],
    [ "VariantTypeResolver", "struction_1_1base_1_1_variant_type_resolver.html", "struction_1_1base_1_1_variant_type_resolver" ],
    [ "VectorDataContainer", "classion_1_1base_1_1_vector_data_container.html", "classion_1_1base_1_1_vector_data_container" ],
    [ "WeakReferent", "classion_1_1base_1_1_weak_referent.html", "classion_1_1base_1_1_weak_referent" ],
    [ "WeakReferentPtr", "classion_1_1base_1_1_weak_referent_ptr.html", "classion_1_1base_1_1_weak_referent_ptr" ],
    [ "WorkerPool", "classion_1_1base_1_1_worker_pool.html", "classion_1_1base_1_1_worker_pool" ],
    [ "ZipAssetManager", "classion_1_1base_1_1_zip_asset_manager.html", "classion_1_1base_1_1_zip_asset_manager" ]
];